using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LibraryManagementSystem.Core.Entities
{
    public class Member
    {
        // Member ID is typically auto-generated by the database.
        public int MemberID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string MemberType { get; set; }
        public DateTime RegDate { get; set; }
        public DateTime ExpDate { get; set; }

        public string Status { get; set; } = "Active"; // Default status
    }
}

