namespace Project5LMS.Forms.Admin.Catalog
{
    partial class AdminCatalogNewBookForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.panelMainContainer = new System.Windows.Forms.Panel();
            this.panelContent = new System.Windows.Forms.Panel();
            this.panelBookType = new System.Windows.Forms.Panel();
            this.radioReferenceBook = new System.Windows.Forms.RadioButton();
            this.panelReferenceBookCard = new System.Windows.Forms.Panel();
            this.lblReferenceBookDesc = new System.Windows.Forms.Label();
            this.lblReferenceBookTitle = new System.Windows.Forms.Label();
            this.radioCirculationBook = new System.Windows.Forms.RadioButton();
            this.panelCirculationBookCard = new System.Windows.Forms.Panel();
            this.lblCirculationBookDesc = new System.Windows.Forms.Label();
            this.lblCirculationBookTitle = new System.Windows.Forms.Label();
            this.lblBookType = new System.Windows.Forms.Label();
            this.panelBookCover = new System.Windows.Forms.Panel();
            this.lblFileInfo = new System.Windows.Forms.Label();
            this.lblUploadText = new System.Windows.Forms.Label();
            this.panelUploadArea = new System.Windows.Forms.Panel();
            this.picBookCover = new System.Windows.Forms.PictureBox();
            this.lblBookCover = new System.Windows.Forms.Label();
            this.panelLocationCopies = new System.Windows.Forms.Panel();
            this.btnDecreaseCopies = new System.Windows.Forms.Button();
            this.btnIncreaseCopies = new System.Windows.Forms.Button();
            this.txtNumberOfCopies = new System.Windows.Forms.TextBox();
            this.lblNumberOfCopies = new System.Windows.Forms.Label();
            this.txtShelfLocation = new System.Windows.Forms.TextBox();
            this.lblShelfLocation = new System.Windows.Forms.Label();
            this.lblLocationCopies = new System.Windows.Forms.Label();
            this.panelPhysicalDescription = new System.Windows.Forms.Panel();
            this.txtPhysicalDescription = new System.Windows.Forms.TextBox();
            this.lblPhysicalDescription = new System.Windows.Forms.Label();
            this.txtNumberOfPages = new System.Windows.Forms.TextBox();
            this.lblNumberOfPages = new System.Windows.Forms.Label();
            this.lblPhysicalDesc = new System.Windows.Forms.Label();
            this.panelClassification = new System.Windows.Forms.Panel();
            this.cmbLanguage = new System.Windows.Forms.ComboBox();
            this.lblLanguage = new System.Windows.Forms.Label();
            this.txtSubjectClassification = new System.Windows.Forms.TextBox();
            this.lblSubjectClassification = new System.Windows.Forms.Label();
            this.cmbCategory = new System.Windows.Forms.ComboBox();
            this.lblCategory = new System.Windows.Forms.Label();
            this.lblClassification = new System.Windows.Forms.Label();
            this.panelPublicationInfo = new System.Windows.Forms.Panel();
            this.txtEdition = new System.Windows.Forms.TextBox();
            this.lblEdition = new System.Windows.Forms.Label();
            this.txtPublicationYear = new System.Windows.Forms.TextBox();
            this.lblPublicationYear = new System.Windows.Forms.Label();
            this.txtPublisher = new System.Windows.Forms.TextBox();
            this.lblPublisher = new System.Windows.Forms.Label();
            this.lblPublicationInfo = new System.Windows.Forms.Label();
            this.panelBookDetails = new System.Windows.Forms.Panel();
            this.txtEditors = new System.Windows.Forms.TextBox();
            this.lblEditors = new System.Windows.Forms.Label();
            this.txtAuthors = new System.Windows.Forms.TextBox();
            this.lblAuthors = new System.Windows.Forms.Label();
            this.txtSubtitle = new System.Windows.Forms.TextBox();
            this.lblSubtitle = new System.Windows.Forms.Label();
            this.txtTitle = new System.Windows.Forms.TextBox();
            this.lblTitle = new System.Windows.Forms.Label();
            this.panelBookIdentification = new System.Windows.Forms.Panel();
            this.txtCallNumber = new System.Windows.Forms.TextBox();
            this.lblCallNumber = new System.Windows.Forms.Label();
            this.txtISBN = new System.Windows.Forms.TextBox();
            this.lblISBN = new System.Windows.Forms.Label();
            this.txtAccessionNumber = new System.Windows.Forms.TextBox();
            this.lblAccessionNumber = new System.Windows.Forms.Label();
            this.lblBookIdentification = new System.Windows.Forms.Label();
            this.lblBookDetails = new System.Windows.Forms.Label();
            this.panelHeader = new System.Windows.Forms.Panel();
            this.btnClose = new System.Windows.Forms.Button();
            this.lblFormTitle = new System.Windows.Forms.Label();
            this.panelFooter = new System.Windows.Forms.Panel();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnAddBook = new System.Windows.Forms.Button();
            this.panelMainContainer.SuspendLayout();
            this.panelContent.SuspendLayout();
            this.panelBookType.SuspendLayout();
            this.panelReferenceBookCard.SuspendLayout();
            this.panelCirculationBookCard.SuspendLayout();
            this.panelBookCover.SuspendLayout();
            this.panelUploadArea.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picBookCover)).BeginInit();
            this.panelLocationCopies.SuspendLayout();
            this.panelPhysicalDescription.SuspendLayout();
            this.panelClassification.SuspendLayout();
            this.panelPublicationInfo.SuspendLayout();
            this.panelBookDetails.SuspendLayout();
            this.panelBookIdentification.SuspendLayout();
            this.panelHeader.SuspendLayout();
            this.panelFooter.SuspendLayout();
            this.SuspendLayout();
            this.panelMainContainer.AutoScroll = true;
            this.panelMainContainer.BackColor = System.Drawing.Color.White;
            this.panelMainContainer.Controls.Add(this.panelContent);
            this.panelMainContainer.Controls.Add(this.panelHeader);
            this.panelMainContainer.Controls.Add(this.panelFooter);
            this.panelMainContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMainContainer.Location = new System.Drawing.Point(0, 0);
            this.panelMainContainer.Margin = new System.Windows.Forms.Padding(4);
            this.panelMainContainer.Name = "panelMainContainer";
            this.panelMainContainer.Size = new System.Drawing.Size(1000, 900);
            this.panelMainContainer.TabIndex = 0;
            this.panelContent.AutoScroll = true;
            this.panelContent.BackColor = System.Drawing.Color.White;
            this.panelContent.Controls.Add(this.panelBookType);
            this.panelContent.Controls.Add(this.panelBookCover);
            this.panelContent.Controls.Add(this.panelLocationCopies);
            this.panelContent.Controls.Add(this.panelPhysicalDescription);
            this.panelContent.Controls.Add(this.panelClassification);
            this.panelContent.Controls.Add(this.panelPublicationInfo);
            this.panelContent.Controls.Add(this.panelBookDetails);
            this.panelContent.Controls.Add(this.panelBookIdentification);
            this.panelContent.Controls.Add(this.lblBookDetails);
            this.panelContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelContent.Location = new System.Drawing.Point(0, 60);
            this.panelContent.Margin = new System.Windows.Forms.Padding(4);
            this.panelContent.Name = "panelContent";
            this.panelContent.Padding = new System.Windows.Forms.Padding(40, 20, 40, 20);
            this.panelContent.Size = new System.Drawing.Size(1000, 800);
            this.panelContent.TabIndex = 2;
            this.panelBookType.BackColor = System.Drawing.Color.White;
            this.panelBookType.Controls.Add(this.radioReferenceBook);
            this.panelBookType.Controls.Add(this.panelReferenceBookCard);
            this.panelBookType.Controls.Add(this.radioCirculationBook);
            this.panelBookType.Controls.Add(this.panelCirculationBookCard);
            this.panelBookType.Controls.Add(this.lblBookType);
            this.panelBookType.Location = new System.Drawing.Point(41, 1095);
            this.panelBookType.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelBookType.Name = "panelBookType";
            this.panelBookType.Size = new System.Drawing.Size(920, 120);
            this.panelBookType.TabIndex = 7;
            this.radioReferenceBook.AutoSize = true;
            this.radioReferenceBook.Location = new System.Drawing.Point(500, 50);
            this.radioReferenceBook.Margin = new System.Windows.Forms.Padding(4);
            this.radioReferenceBook.Name = "radioReferenceBook";
            this.radioReferenceBook.Size = new System.Drawing.Size(17, 16);
            this.radioReferenceBook.TabIndex = 4;
            this.radioReferenceBook.TabStop = true;
            this.radioReferenceBook.UseVisualStyleBackColor = true;
            this.radioReferenceBook.CheckedChanged += new System.EventHandler(this.radioReferenceBook_CheckedChanged);
            this.panelReferenceBookCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(249)))), ((int)(((byte)(250)))));
            this.panelReferenceBookCard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelReferenceBookCard.Controls.Add(this.lblReferenceBookDesc);
            this.panelReferenceBookCard.Controls.Add(this.lblReferenceBookTitle);
            this.panelReferenceBookCard.Location = new System.Drawing.Point(530, 30);
            this.panelReferenceBookCard.Margin = new System.Windows.Forms.Padding(4);
            this.panelReferenceBookCard.Name = "panelReferenceBookCard";
            this.panelReferenceBookCard.Padding = new System.Windows.Forms.Padding(20);
            this.panelReferenceBookCard.Size = new System.Drawing.Size(380, 80);
            this.panelReferenceBookCard.TabIndex = 3;
            this.panelReferenceBookCard.Click += new System.EventHandler(this.panelReferenceBookCard_Click);
            this.lblReferenceBookDesc.AutoSize = true;
            this.lblReferenceBookDesc.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblReferenceBookDesc.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblReferenceBookDesc.Location = new System.Drawing.Point(20, 45);
            this.lblReferenceBookDesc.Margin = new System.Windows.Forms.Padding(0);
            this.lblReferenceBookDesc.Name = "lblReferenceBookDesc";
            this.lblReferenceBookDesc.Size = new System.Drawing.Size(112, 20);
            this.lblReferenceBookDesc.TabIndex = 1;
            this.lblReferenceBookDesc.Text = "Library use only";
            this.lblReferenceBookDesc.Click += new System.EventHandler(this.panelReferenceBookCard_Click);
            this.lblReferenceBookTitle.AutoSize = true;
            this.lblReferenceBookTitle.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblReferenceBookTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblReferenceBookTitle.Location = new System.Drawing.Point(20, 15);
            this.lblReferenceBookTitle.Margin = new System.Windows.Forms.Padding(0);
            this.lblReferenceBookTitle.Name = "lblReferenceBookTitle";
            this.lblReferenceBookTitle.Size = new System.Drawing.Size(152, 25);
            this.lblReferenceBookTitle.TabIndex = 0;
            this.lblReferenceBookTitle.Text = "Reference Book";
            this.lblReferenceBookTitle.Click += new System.EventHandler(this.panelReferenceBookCard_Click);
            this.radioCirculationBook.AutoSize = true;
            this.radioCirculationBook.Checked = true;
            this.radioCirculationBook.Location = new System.Drawing.Point(20, 50);
            this.radioCirculationBook.Margin = new System.Windows.Forms.Padding(4);
            this.radioCirculationBook.Name = "radioCirculationBook";
            this.radioCirculationBook.Size = new System.Drawing.Size(17, 16);
            this.radioCirculationBook.TabIndex = 2;
            this.radioCirculationBook.TabStop = true;
            this.radioCirculationBook.UseVisualStyleBackColor = true;
            this.radioCirculationBook.CheckedChanged += new System.EventHandler(this.radioCirculationBook_CheckedChanged);
            this.panelCirculationBookCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(249)))), ((int)(((byte)(250)))));
            this.panelCirculationBookCard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelCirculationBookCard.Controls.Add(this.lblCirculationBookDesc);
            this.panelCirculationBookCard.Controls.Add(this.lblCirculationBookTitle);
            this.panelCirculationBookCard.Location = new System.Drawing.Point(50, 30);
            this.panelCirculationBookCard.Margin = new System.Windows.Forms.Padding(4);
            this.panelCirculationBookCard.Name = "panelCirculationBookCard";
            this.panelCirculationBookCard.Padding = new System.Windows.Forms.Padding(20);
            this.panelCirculationBookCard.Size = new System.Drawing.Size(380, 80);
            this.panelCirculationBookCard.TabIndex = 1;
            this.panelCirculationBookCard.Click += new System.EventHandler(this.panelCirculationBookCard_Click);
            this.lblCirculationBookDesc.AutoSize = true;
            this.lblCirculationBookDesc.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCirculationBookDesc.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblCirculationBookDesc.Location = new System.Drawing.Point(20, 45);
            this.lblCirculationBookDesc.Margin = new System.Windows.Forms.Padding(0);
            this.lblCirculationBookDesc.Name = "lblCirculationBookDesc";
            this.lblCirculationBookDesc.Size = new System.Drawing.Size(210, 20);
            this.lblCirculationBookDesc.TabIndex = 1;
            this.lblCirculationBookDesc.Text = "Can be borrowed by members";
            this.lblCirculationBookDesc.Click += new System.EventHandler(this.panelCirculationBookCard_Click);
            this.lblCirculationBookTitle.AutoSize = true;
            this.lblCirculationBookTitle.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCirculationBookTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblCirculationBookTitle.Location = new System.Drawing.Point(20, 15);
            this.lblCirculationBookTitle.Margin = new System.Windows.Forms.Padding(0);
            this.lblCirculationBookTitle.Name = "lblCirculationBookTitle";
            this.lblCirculationBookTitle.Size = new System.Drawing.Size(161, 25);
            this.lblCirculationBookTitle.TabIndex = 0;
            this.lblCirculationBookTitle.Text = "Circulation Book";
            this.lblCirculationBookTitle.Click += new System.EventHandler(this.panelCirculationBookCard_Click);
            this.lblBookType.AutoSize = true;
            this.lblBookType.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBookType.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBookType.Location = new System.Drawing.Point(0, 0);
            this.lblBookType.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblBookType.Name = "lblBookType";
            this.lblBookType.Size = new System.Drawing.Size(111, 28);
            this.lblBookType.TabIndex = 0;
            this.lblBookType.Text = "Book Type";
            this.panelBookCover.BackColor = System.Drawing.Color.White;
            this.panelBookCover.Controls.Add(this.lblFileInfo);
            this.panelBookCover.Controls.Add(this.lblUploadText);
            this.panelBookCover.Controls.Add(this.panelUploadArea);
            this.panelBookCover.Controls.Add(this.lblBookCover);
            this.panelBookCover.Location = new System.Drawing.Point(40, 860);
            this.panelBookCover.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelBookCover.Name = "panelBookCover";
            this.panelBookCover.Size = new System.Drawing.Size(920, 215);
            this.panelBookCover.TabIndex = 6;
            this.lblFileInfo.AutoSize = true;
            this.lblFileInfo.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFileInfo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblFileInfo.Location = new System.Drawing.Point(280, 80);
            this.lblFileInfo.Margin = new System.Windows.Forms.Padding(0);
            this.lblFileInfo.Name = "lblFileInfo";
            this.lblFileInfo.Size = new System.Drawing.Size(141, 20);
            this.lblFileInfo.TabIndex = 3;
            this.lblFileInfo.Text = "PNG, JPG up to 5MB";
            this.lblUploadText.AutoSize = true;
            this.lblUploadText.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUploadText.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblUploadText.Location = new System.Drawing.Point(280, 55);
            this.lblUploadText.Margin = new System.Windows.Forms.Padding(0);
            this.lblUploadText.Name = "lblUploadText";
            this.lblUploadText.Size = new System.Drawing.Size(213, 23);
            this.lblUploadText.TabIndex = 2;
            this.lblUploadText.Text = "Click to upload book cover";
            this.panelUploadArea.BackColor = System.Drawing.Color.White;
            this.panelUploadArea.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelUploadArea.Controls.Add(this.picBookCover);
            this.panelUploadArea.Cursor = System.Windows.Forms.Cursors.Hand;
            this.panelUploadArea.Location = new System.Drawing.Point(0, 40);
            this.panelUploadArea.Margin = new System.Windows.Forms.Padding(0);
            this.panelUploadArea.Name = "panelUploadArea";
            this.panelUploadArea.Size = new System.Drawing.Size(250, 150);
            this.panelUploadArea.TabIndex = 1;
            this.panelUploadArea.Click += new System.EventHandler(this.panelUploadArea_Click);
            this.panelUploadArea.Paint += new System.Windows.Forms.PaintEventHandler(this.panelUploadArea_Paint);
            this.picBookCover.BackColor = System.Drawing.Color.Transparent;
            this.picBookCover.Dock = System.Windows.Forms.DockStyle.Fill;
            this.picBookCover.Location = new System.Drawing.Point(0, 0);
            this.picBookCover.Margin = new System.Windows.Forms.Padding(4);
            this.picBookCover.Name = "picBookCover";
            this.picBookCover.Size = new System.Drawing.Size(248, 148);
            this.picBookCover.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picBookCover.TabIndex = 0;
            this.picBookCover.TabStop = false;
            this.picBookCover.Visible = false;
            this.picBookCover.Click += new System.EventHandler(this.panelUploadArea_Click);
            this.lblBookCover.AutoSize = true;
            this.lblBookCover.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBookCover.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBookCover.Location = new System.Drawing.Point(0, 0);
            this.lblBookCover.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblBookCover.Name = "lblBookCover";
            this.lblBookCover.Size = new System.Drawing.Size(120, 28);
            this.lblBookCover.TabIndex = 0;
            this.lblBookCover.Text = "Book Cover";
            this.panelLocationCopies.BackColor = System.Drawing.Color.White;
            this.panelLocationCopies.Controls.Add(this.btnDecreaseCopies);
            this.panelLocationCopies.Controls.Add(this.btnIncreaseCopies);
            this.panelLocationCopies.Controls.Add(this.txtNumberOfCopies);
            this.panelLocationCopies.Controls.Add(this.lblNumberOfCopies);
            this.panelLocationCopies.Controls.Add(this.txtShelfLocation);
            this.panelLocationCopies.Controls.Add(this.lblShelfLocation);
            this.panelLocationCopies.Controls.Add(this.lblLocationCopies);
            this.panelLocationCopies.Location = new System.Drawing.Point(40, 740);
            this.panelLocationCopies.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelLocationCopies.Name = "panelLocationCopies";
            this.panelLocationCopies.Size = new System.Drawing.Size(920, 100);
            this.panelLocationCopies.TabIndex = 5;
            this.btnDecreaseCopies.BackColor = System.Drawing.Color.White;
            this.btnDecreaseCopies.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnDecreaseCopies.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDecreaseCopies.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDecreaseCopies.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnDecreaseCopies.Location = new System.Drawing.Point(500, 50);
            this.btnDecreaseCopies.Margin = new System.Windows.Forms.Padding(0);
            this.btnDecreaseCopies.Name = "btnDecreaseCopies";
            this.btnDecreaseCopies.Size = new System.Drawing.Size(40, 40);
            this.btnDecreaseCopies.TabIndex = 6;
            this.btnDecreaseCopies.Text = "-";
            this.btnDecreaseCopies.UseVisualStyleBackColor = false;
            this.btnDecreaseCopies.Click += new System.EventHandler(this.btnDecreaseCopies_Click);
            this.btnIncreaseCopies.BackColor = System.Drawing.Color.White;
            this.btnIncreaseCopies.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnIncreaseCopies.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnIncreaseCopies.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnIncreaseCopies.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnIncreaseCopies.Location = new System.Drawing.Point(600, 50);
            this.btnIncreaseCopies.Margin = new System.Windows.Forms.Padding(0);
            this.btnIncreaseCopies.Name = "btnIncreaseCopies";
            this.btnIncreaseCopies.Size = new System.Drawing.Size(40, 40);
            this.btnIncreaseCopies.TabIndex = 5;
            this.btnIncreaseCopies.Text = "+";
            this.btnIncreaseCopies.UseVisualStyleBackColor = false;
            this.btnIncreaseCopies.Click += new System.EventHandler(this.btnIncreaseCopies_Click);
            this.txtNumberOfCopies.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNumberOfCopies.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNumberOfCopies.Location = new System.Drawing.Point(540, 50);
            this.txtNumberOfCopies.Margin = new System.Windows.Forms.Padding(0);
            this.txtNumberOfCopies.Name = "txtNumberOfCopies";
            this.txtNumberOfCopies.Size = new System.Drawing.Size(60, 30);
            this.txtNumberOfCopies.TabIndex = 4;
            this.txtNumberOfCopies.Text = "1";
            this.txtNumberOfCopies.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.lblNumberOfCopies.AutoSize = true;
            this.lblNumberOfCopies.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNumberOfCopies.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblNumberOfCopies.Location = new System.Drawing.Point(500, 25);
            this.lblNumberOfCopies.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblNumberOfCopies.Name = "lblNumberOfCopies";
            this.lblNumberOfCopies.Size = new System.Drawing.Size(161, 23);
            this.lblNumberOfCopies.TabIndex = 3;
            this.lblNumberOfCopies.Text = "Number of Copies *";
            this.txtShelfLocation.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtShelfLocation.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtShelfLocation.Location = new System.Drawing.Point(0, 50);
            this.txtShelfLocation.Margin = new System.Windows.Forms.Padding(0);
            this.txtShelfLocation.Name = "txtShelfLocation";
            this.txtShelfLocation.Size = new System.Drawing.Size(420, 30);
            this.txtShelfLocation.TabIndex = 2;
            this.lblShelfLocation.AutoSize = true;
            this.lblShelfLocation.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblShelfLocation.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblShelfLocation.Location = new System.Drawing.Point(0, 25);
            this.lblShelfLocation.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblShelfLocation.Name = "lblShelfLocation";
            this.lblShelfLocation.Size = new System.Drawing.Size(129, 23);
            this.lblShelfLocation.TabIndex = 1;
            this.lblShelfLocation.Text = "Shelf Location *";
            this.lblLocationCopies.AutoSize = true;
            this.lblLocationCopies.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLocationCopies.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblLocationCopies.Location = new System.Drawing.Point(0, 0);
            this.lblLocationCopies.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblLocationCopies.Name = "lblLocationCopies";
            this.lblLocationCopies.Size = new System.Drawing.Size(167, 28);
            this.lblLocationCopies.TabIndex = 0;
            this.lblLocationCopies.Text = "Location & Copies";
            this.panelPhysicalDescription.BackColor = System.Drawing.Color.White;
            this.panelPhysicalDescription.Controls.Add(this.txtPhysicalDescription);
            this.panelPhysicalDescription.Controls.Add(this.lblPhysicalDescription);
            this.panelPhysicalDescription.Controls.Add(this.txtNumberOfPages);
            this.panelPhysicalDescription.Controls.Add(this.lblNumberOfPages);
            this.panelPhysicalDescription.Controls.Add(this.lblPhysicalDesc);
            this.panelPhysicalDescription.Location = new System.Drawing.Point(40, 620);
            this.panelPhysicalDescription.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelPhysicalDescription.Name = "panelPhysicalDescription";
            this.panelPhysicalDescription.Size = new System.Drawing.Size(920, 100);
            this.panelPhysicalDescription.TabIndex = 4;
            this.txtPhysicalDescription.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPhysicalDescription.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPhysicalDescription.Location = new System.Drawing.Point(500, 50);
            this.txtPhysicalDescription.Margin = new System.Windows.Forms.Padding(0);
            this.txtPhysicalDescription.Name = "txtPhysicalDescription";
            this.txtPhysicalDescription.Size = new System.Drawing.Size(420, 30);
            this.txtPhysicalDescription.TabIndex = 4;
            this.lblPhysicalDescription.AutoSize = true;
            this.lblPhysicalDescription.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPhysicalDescription.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPhysicalDescription.Location = new System.Drawing.Point(500, 25);
            this.lblPhysicalDescription.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblPhysicalDescription.Name = "lblPhysicalDescription";
            this.lblPhysicalDescription.Size = new System.Drawing.Size(161, 23);
            this.lblPhysicalDescription.TabIndex = 3;
            this.lblPhysicalDescription.Text = "Physical Description";
            this.txtNumberOfPages.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtNumberOfPages.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNumberOfPages.Location = new System.Drawing.Point(0, 50);
            this.txtNumberOfPages.Margin = new System.Windows.Forms.Padding(0);
            this.txtNumberOfPages.Name = "txtNumberOfPages";
            this.txtNumberOfPages.Size = new System.Drawing.Size(420, 30);
            this.txtNumberOfPages.TabIndex = 2;
            this.txtNumberOfPages.Text = "0";
            this.lblNumberOfPages.AutoSize = true;
            this.lblNumberOfPages.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNumberOfPages.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblNumberOfPages.Location = new System.Drawing.Point(0, 25);
            this.lblNumberOfPages.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblNumberOfPages.Name = "lblNumberOfPages";
            this.lblNumberOfPages.Size = new System.Drawing.Size(142, 23);
            this.lblNumberOfPages.TabIndex = 1;
            this.lblNumberOfPages.Text = "Number of Pages";
            this.lblPhysicalDesc.AutoSize = true;
            this.lblPhysicalDesc.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPhysicalDesc.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPhysicalDesc.Location = new System.Drawing.Point(0, 0);
            this.lblPhysicalDesc.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblPhysicalDesc.Name = "lblPhysicalDesc";
            this.lblPhysicalDesc.Size = new System.Drawing.Size(204, 28);
            this.lblPhysicalDesc.TabIndex = 0;
            this.lblPhysicalDesc.Text = "Physical Description";
            this.panelClassification.BackColor = System.Drawing.Color.White;
            this.panelClassification.Controls.Add(this.cmbLanguage);
            this.panelClassification.Controls.Add(this.lblLanguage);
            this.panelClassification.Controls.Add(this.txtSubjectClassification);
            this.panelClassification.Controls.Add(this.lblSubjectClassification);
            this.panelClassification.Controls.Add(this.cmbCategory);
            this.panelClassification.Controls.Add(this.lblCategory);
            this.panelClassification.Controls.Add(this.lblClassification);
            this.panelClassification.Location = new System.Drawing.Point(41, 500);
            this.panelClassification.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelClassification.Name = "panelClassification";
            this.panelClassification.Size = new System.Drawing.Size(920, 100);
            this.panelClassification.TabIndex = 3;
            this.cmbLanguage.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbLanguage.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbLanguage.FormattingEnabled = true;
            this.cmbLanguage.Location = new System.Drawing.Point(500, 50);
            this.cmbLanguage.Margin = new System.Windows.Forms.Padding(0);
            this.cmbLanguage.Name = "cmbLanguage";
            this.cmbLanguage.Size = new System.Drawing.Size(420, 31);
            this.cmbLanguage.TabIndex = 6;
            this.lblLanguage.AutoSize = true;
            this.lblLanguage.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLanguage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblLanguage.Location = new System.Drawing.Point(500, 25);
            this.lblLanguage.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblLanguage.Name = "lblLanguage";
            this.lblLanguage.Size = new System.Drawing.Size(97, 23);
            this.lblLanguage.TabIndex = 5;
            this.lblLanguage.Text = "Language *";
            this.txtSubjectClassification.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtSubjectClassification.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSubjectClassification.Location = new System.Drawing.Point(250, 50);
            this.txtSubjectClassification.Margin = new System.Windows.Forms.Padding(0);
            this.txtSubjectClassification.Name = "txtSubjectClassification";
            this.txtSubjectClassification.Size = new System.Drawing.Size(200, 30);
            this.txtSubjectClassification.TabIndex = 4;
            this.lblSubjectClassification.AutoSize = true;
            this.lblSubjectClassification.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSubjectClassification.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblSubjectClassification.Location = new System.Drawing.Point(250, 25);
            this.lblSubjectClassification.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblSubjectClassification.Name = "lblSubjectClassification";
            this.lblSubjectClassification.Size = new System.Drawing.Size(169, 23);
            this.lblSubjectClassification.TabIndex = 3;
            this.lblSubjectClassification.Text = "Subject Classification";
            this.cmbCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCategory.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbCategory.FormattingEnabled = true;
            this.cmbCategory.Location = new System.Drawing.Point(0, 50);
            this.cmbCategory.Margin = new System.Windows.Forms.Padding(0);
            this.cmbCategory.Name = "cmbCategory";
            this.cmbCategory.Size = new System.Drawing.Size(200, 31);
            this.cmbCategory.TabIndex = 2;
            this.lblCategory.AutoSize = true;
            this.lblCategory.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCategory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblCategory.Location = new System.Drawing.Point(0, 25);
            this.lblCategory.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblCategory.Name = "lblCategory";
            this.lblCategory.Size = new System.Drawing.Size(91, 23);
            this.lblCategory.TabIndex = 1;
            this.lblCategory.Text = "Category *";
            this.lblClassification.AutoSize = true;
            this.lblClassification.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblClassification.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblClassification.Location = new System.Drawing.Point(-1, 0);
            this.lblClassification.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblClassification.Name = "lblClassification";
            this.lblClassification.Size = new System.Drawing.Size(138, 28);
            this.lblClassification.TabIndex = 0;
            this.lblClassification.Text = "Classification";
            this.panelPublicationInfo.BackColor = System.Drawing.Color.White;
            this.panelPublicationInfo.Controls.Add(this.txtEdition);
            this.panelPublicationInfo.Controls.Add(this.lblEdition);
            this.panelPublicationInfo.Controls.Add(this.txtPublicationYear);
            this.panelPublicationInfo.Controls.Add(this.lblPublicationYear);
            this.panelPublicationInfo.Controls.Add(this.txtPublisher);
            this.panelPublicationInfo.Controls.Add(this.lblPublisher);
            this.panelPublicationInfo.Controls.Add(this.lblPublicationInfo);
            this.panelPublicationInfo.Location = new System.Drawing.Point(40, 380);
            this.panelPublicationInfo.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelPublicationInfo.Name = "panelPublicationInfo";
            this.panelPublicationInfo.Size = new System.Drawing.Size(920, 100);
            this.panelPublicationInfo.TabIndex = 2;
            this.txtEdition.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtEdition.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEdition.Location = new System.Drawing.Point(500, 50);
            this.txtEdition.Margin = new System.Windows.Forms.Padding(0);
            this.txtEdition.Name = "txtEdition";
            this.txtEdition.Size = new System.Drawing.Size(420, 30);
            this.txtEdition.TabIndex = 6;
            this.lblEdition.AutoSize = true;
            this.lblEdition.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblEdition.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblEdition.Location = new System.Drawing.Point(500, 25);
            this.lblEdition.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblEdition.Name = "lblEdition";
            this.lblEdition.Size = new System.Drawing.Size(63, 23);
            this.lblEdition.TabIndex = 5;
            this.lblEdition.Text = "Edition";
            this.txtPublicationYear.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPublicationYear.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPublicationYear.Location = new System.Drawing.Point(250, 50);
            this.txtPublicationYear.Margin = new System.Windows.Forms.Padding(0);
            this.txtPublicationYear.Name = "txtPublicationYear";
            this.txtPublicationYear.Size = new System.Drawing.Size(200, 30);
            this.txtPublicationYear.TabIndex = 4;
            this.txtPublicationYear.Text = "2026";
            this.lblPublicationYear.AutoSize = true;
            this.lblPublicationYear.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPublicationYear.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPublicationYear.Location = new System.Drawing.Point(250, 25);
            this.lblPublicationYear.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblPublicationYear.Name = "lblPublicationYear";
            this.lblPublicationYear.Size = new System.Drawing.Size(144, 23);
            this.lblPublicationYear.TabIndex = 3;
            this.lblPublicationYear.Text = "Publication Year *";
            this.txtPublisher.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtPublisher.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPublisher.Location = new System.Drawing.Point(0, 50);
            this.txtPublisher.Margin = new System.Windows.Forms.Padding(0);
            this.txtPublisher.Name = "txtPublisher";
            this.txtPublisher.Size = new System.Drawing.Size(200, 30);
            this.txtPublisher.TabIndex = 2;
            this.lblPublisher.AutoSize = true;
            this.lblPublisher.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPublisher.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPublisher.Location = new System.Drawing.Point(0, 25);
            this.lblPublisher.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblPublisher.Name = "lblPublisher";
            this.lblPublisher.Size = new System.Drawing.Size(92, 23);
            this.lblPublisher.TabIndex = 1;
            this.lblPublisher.Text = "Publisher *";
            this.lblPublicationInfo.AutoSize = true;
            this.lblPublicationInfo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPublicationInfo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPublicationInfo.Location = new System.Drawing.Point(2, 0);
            this.lblPublicationInfo.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblPublicationInfo.Name = "lblPublicationInfo";
            this.lblPublicationInfo.Size = new System.Drawing.Size(238, 28);
            this.lblPublicationInfo.TabIndex = 0;
            this.lblPublicationInfo.Text = "Publication Information";
            this.panelBookDetails.BackColor = System.Drawing.Color.White;
            this.panelBookDetails.Controls.Add(this.txtEditors);
            this.panelBookDetails.Controls.Add(this.lblEditors);
            this.panelBookDetails.Controls.Add(this.txtAuthors);
            this.panelBookDetails.Controls.Add(this.lblAuthors);
            this.panelBookDetails.Controls.Add(this.txtSubtitle);
            this.panelBookDetails.Controls.Add(this.lblSubtitle);
            this.panelBookDetails.Controls.Add(this.txtTitle);
            this.panelBookDetails.Controls.Add(this.lblTitle);
            this.panelBookDetails.Location = new System.Drawing.Point(40, 162);
            this.panelBookDetails.Margin = new System.Windows.Forms.Padding(0, 20, 0, 0);
            this.panelBookDetails.Name = "panelBookDetails";
            this.panelBookDetails.Size = new System.Drawing.Size(920, 198);
            this.panelBookDetails.TabIndex = 1;
            this.txtEditors.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtEditors.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEditors.Location = new System.Drawing.Point(500, 150);
            this.txtEditors.Margin = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.txtEditors.Name = "txtEditors";
            this.txtEditors.Size = new System.Drawing.Size(420, 30);
            this.txtEditors.TabIndex = 8;
            this.lblEditors.AutoSize = true;
            this.lblEditors.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblEditors.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblEditors.Location = new System.Drawing.Point(500, 125);
            this.lblEditors.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblEditors.Name = "lblEditors";
            this.lblEditors.Size = new System.Drawing.Size(72, 23);
            this.lblEditors.TabIndex = 7;
            this.lblEditors.Text = "Editor(s)";
            this.txtAuthors.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtAuthors.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAuthors.Location = new System.Drawing.Point(0, 150);
            this.txtAuthors.Margin = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.txtAuthors.Name = "txtAuthors";
            this.txtAuthors.Size = new System.Drawing.Size(420, 30);
            this.txtAuthors.TabIndex = 6;
            this.lblAuthors.AutoSize = true;
            this.lblAuthors.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAuthors.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblAuthors.Location = new System.Drawing.Point(0, 125);
            this.lblAuthors.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblAuthors.Name = "lblAuthors";
            this.lblAuthors.Size = new System.Drawing.Size(92, 23);
            this.lblAuthors.TabIndex = 5;
            this.lblAuthors.Text = "Author(s) *";
            this.txtSubtitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtSubtitle.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSubtitle.Location = new System.Drawing.Point(0, 80);
            this.txtSubtitle.Margin = new System.Windows.Forms.Padding(0, 10, 0, 0);
            this.txtSubtitle.Name = "txtSubtitle";
            this.txtSubtitle.Size = new System.Drawing.Size(920, 30);
            this.txtSubtitle.TabIndex = 4;
            this.lblSubtitle.AutoSize = true;
            this.lblSubtitle.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblSubtitle.Location = new System.Drawing.Point(0, 55);
            this.lblSubtitle.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblSubtitle.Name = "lblSubtitle";
            this.lblSubtitle.Size = new System.Drawing.Size(68, 23);
            this.lblSubtitle.TabIndex = 3;
            this.lblSubtitle.Text = "Subtitle";
            this.txtTitle.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtTitle.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTitle.Location = new System.Drawing.Point(0, 25);
            this.txtTitle.Margin = new System.Windows.Forms.Padding(0);
            this.txtTitle.Name = "txtTitle";
            this.txtTitle.Size = new System.Drawing.Size(920, 30);
            this.txtTitle.TabIndex = 2;
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(54, 23);
            this.lblTitle.TabIndex = 1;
            this.lblTitle.Text = "Title *";
            this.panelBookIdentification.BackColor = System.Drawing.Color.White;
            this.panelBookIdentification.Controls.Add(this.txtCallNumber);
            this.panelBookIdentification.Controls.Add(this.lblCallNumber);
            this.panelBookIdentification.Controls.Add(this.txtISBN);
            this.panelBookIdentification.Controls.Add(this.lblISBN);
            this.panelBookIdentification.Controls.Add(this.txtAccessionNumber);
            this.panelBookIdentification.Controls.Add(this.lblAccessionNumber);
            this.panelBookIdentification.Controls.Add(this.lblBookIdentification);
            this.panelBookIdentification.Location = new System.Drawing.Point(40, 20);
            this.panelBookIdentification.Margin = new System.Windows.Forms.Padding(0);
            this.panelBookIdentification.Name = "panelBookIdentification";
            this.panelBookIdentification.Size = new System.Drawing.Size(920, 100);
            this.panelBookIdentification.TabIndex = 0;
            this.txtCallNumber.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtCallNumber.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCallNumber.Location = new System.Drawing.Point(500, 50);
            this.txtCallNumber.Margin = new System.Windows.Forms.Padding(0);
            this.txtCallNumber.Name = "txtCallNumber";
            this.txtCallNumber.Size = new System.Drawing.Size(420, 30);
            this.txtCallNumber.TabIndex = 6;
            this.lblCallNumber.AutoSize = true;
            this.lblCallNumber.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCallNumber.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblCallNumber.Location = new System.Drawing.Point(500, 25);
            this.lblCallNumber.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblCallNumber.Name = "lblCallNumber";
            this.lblCallNumber.Size = new System.Drawing.Size(106, 23);
            this.lblCallNumber.TabIndex = 5;
            this.lblCallNumber.Text = "Call Number";
            this.txtISBN.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtISBN.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtISBN.Location = new System.Drawing.Point(250, 50);
            this.txtISBN.Margin = new System.Windows.Forms.Padding(0);
            this.txtISBN.Name = "txtISBN";
            this.txtISBN.Size = new System.Drawing.Size(200, 30);
            this.txtISBN.TabIndex = 4;
            this.txtISBN.Text = "978-0-00-000000-0";
            this.lblISBN.AutoSize = true;
            this.lblISBN.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblISBN.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblISBN.Location = new System.Drawing.Point(250, 25);
            this.lblISBN.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblISBN.Name = "lblISBN";
            this.lblISBN.Size = new System.Drawing.Size(59, 23);
            this.lblISBN.TabIndex = 3;
            this.lblISBN.Text = "ISBN *";
            this.txtAccessionNumber.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtAccessionNumber.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAccessionNumber.Location = new System.Drawing.Point(0, 50);
            this.txtAccessionNumber.Margin = new System.Windows.Forms.Padding(0);
            this.txtAccessionNumber.Name = "txtAccessionNumber";
            this.txtAccessionNumber.Size = new System.Drawing.Size(200, 30);
            this.txtAccessionNumber.TabIndex = 2;
            this.txtAccessionNumber.Text = "ACC-0001";
            this.lblAccessionNumber.AutoSize = true;
            this.lblAccessionNumber.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAccessionNumber.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblAccessionNumber.Location = new System.Drawing.Point(3, 25);
            this.lblAccessionNumber.Margin = new System.Windows.Forms.Padding(0, 0, 0, 5);
            this.lblAccessionNumber.Name = "lblAccessionNumber";
            this.lblAccessionNumber.Size = new System.Drawing.Size(164, 23);
            this.lblAccessionNumber.TabIndex = 1;
            this.lblAccessionNumber.Text = "Accession Number *";
            this.lblBookIdentification.AutoSize = true;
            this.lblBookIdentification.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBookIdentification.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBookIdentification.Location = new System.Drawing.Point(1, 0);
            this.lblBookIdentification.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblBookIdentification.Name = "lblBookIdentification";
            this.lblBookIdentification.Size = new System.Drawing.Size(194, 28);
            this.lblBookIdentification.TabIndex = 0;
            this.lblBookIdentification.Text = "Book Identification";
            this.lblBookDetails.AutoSize = true;
            this.lblBookDetails.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBookDetails.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBookDetails.Location = new System.Drawing.Point(41, 135);
            this.lblBookDetails.Margin = new System.Windows.Forms.Padding(0, 0, 0, 15);
            this.lblBookDetails.Name = "lblBookDetails";
            this.lblBookDetails.Size = new System.Drawing.Size(132, 28);
            this.lblBookDetails.TabIndex = 0;
            this.lblBookDetails.Text = "Book Details";
            this.panelHeader.BackColor = System.Drawing.Color.White;
            this.panelHeader.Controls.Add(this.btnClose);
            this.panelHeader.Controls.Add(this.lblFormTitle);
            this.panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelHeader.Location = new System.Drawing.Point(0, 0);
            this.panelHeader.Margin = new System.Windows.Forms.Padding(4);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Size = new System.Drawing.Size(1000, 60);
            this.panelHeader.TabIndex = 0;
            this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.FlatAppearance.BorderSize = 0;
            this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClose.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.btnClose.Location = new System.Drawing.Point(950, 10);
            this.btnClose.Margin = new System.Windows.Forms.Padding(4);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(40, 40);
            this.btnClose.TabIndex = 1;
            this.btnClose.Text = "�";
            this.btnClose.UseVisualStyleBackColor = false;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            this.lblFormTitle.AutoSize = true;
            this.lblFormTitle.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFormTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblFormTitle.Location = new System.Drawing.Point(20, 15);
            this.lblFormTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblFormTitle.Name = "lblFormTitle";
            this.lblFormTitle.Size = new System.Drawing.Size(208, 37);
            this.lblFormTitle.TabIndex = 0;
            this.lblFormTitle.Text = "Add New Book";
            this.panelFooter.BackColor = System.Drawing.Color.White;
            this.panelFooter.Controls.Add(this.btnCancel);
            this.panelFooter.Controls.Add(this.btnAddBook);
            this.panelFooter.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelFooter.Location = new System.Drawing.Point(0, 860);
            this.panelFooter.Margin = new System.Windows.Forms.Padding(4);
            this.panelFooter.Name = "panelFooter";
            this.panelFooter.Padding = new System.Windows.Forms.Padding(40, 20, 40, 20);
            this.panelFooter.Size = new System.Drawing.Size(1000, 40);
            this.panelFooter.TabIndex = 1;
            this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnCancel.BackColor = System.Drawing.Color.Maroon;
            this.btnCancel.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancel.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.Location = new System.Drawing.Point(40, 0);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(4);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(250, 40);
            this.btnCancel.TabIndex = 0;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.btnAddBook.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddBook.BackColor = System.Drawing.Color.Maroon;
            this.btnAddBook.FlatAppearance.BorderSize = 0;
            this.btnAddBook.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddBook.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddBook.ForeColor = System.Drawing.Color.White;
            this.btnAddBook.Location = new System.Drawing.Point(752, 0);
            this.btnAddBook.Margin = new System.Windows.Forms.Padding(4);
            this.btnAddBook.Name = "btnAddBook";
            this.btnAddBook.Size = new System.Drawing.Size(226, 40);
            this.btnAddBook.TabIndex = 1;
            this.btnAddBook.Text = "Add Book ";
            this.btnAddBook.UseVisualStyleBackColor = false;
            this.btnAddBook.Click += new System.EventHandler(this.btnAddBook_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1000, 900);
            this.Controls.Add(this.panelMainContainer);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "AdminCatalogNewBookForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Add New Book";
            this.Load += new System.EventHandler(this.AdminCatalogNewBookForm_Load);
            this.panelMainContainer.ResumeLayout(false);
            this.panelContent.ResumeLayout(false);
            this.panelContent.PerformLayout();
            this.panelBookType.ResumeLayout(false);
            this.panelBookType.PerformLayout();
            this.panelReferenceBookCard.ResumeLayout(false);
            this.panelReferenceBookCard.PerformLayout();
            this.panelCirculationBookCard.ResumeLayout(false);
            this.panelCirculationBookCard.PerformLayout();
            this.panelBookCover.ResumeLayout(false);
            this.panelBookCover.PerformLayout();
            this.panelUploadArea.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picBookCover)).EndInit();
            this.panelLocationCopies.ResumeLayout(false);
            this.panelLocationCopies.PerformLayout();
            this.panelPhysicalDescription.ResumeLayout(false);
            this.panelPhysicalDescription.PerformLayout();
            this.panelClassification.ResumeLayout(false);
            this.panelClassification.PerformLayout();
            this.panelPublicationInfo.ResumeLayout(false);
            this.panelPublicationInfo.PerformLayout();
            this.panelBookDetails.ResumeLayout(false);
            this.panelBookDetails.PerformLayout();
            this.panelBookIdentification.ResumeLayout(false);
            this.panelBookIdentification.PerformLayout();
            this.panelHeader.ResumeLayout(false);
            this.panelHeader.PerformLayout();
            this.panelFooter.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Panel panelMainContainer;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label lblFormTitle;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Panel panelContent;
        private System.Windows.Forms.Panel panelBookIdentification;
        private System.Windows.Forms.Label lblBookIdentification;
        private System.Windows.Forms.Label lblAccessionNumber;
        private System.Windows.Forms.TextBox txtAccessionNumber;
        private System.Windows.Forms.Label lblISBN;
        private System.Windows.Forms.TextBox txtISBN;
        private System.Windows.Forms.Label lblCallNumber;
        private System.Windows.Forms.TextBox txtCallNumber;
        private System.Windows.Forms.Panel panelBookDetails;
        private System.Windows.Forms.Label lblBookDetails;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.TextBox txtTitle;
        private System.Windows.Forms.Label lblSubtitle;
        private System.Windows.Forms.TextBox txtSubtitle;
        private System.Windows.Forms.Label lblAuthors;
        private System.Windows.Forms.TextBox txtAuthors;
        private System.Windows.Forms.Label lblEditors;
        private System.Windows.Forms.TextBox txtEditors;
        private System.Windows.Forms.Panel panelPublicationInfo;
        private System.Windows.Forms.Label lblPublicationInfo;
        private System.Windows.Forms.Label lblPublisher;
        private System.Windows.Forms.TextBox txtPublisher;
        private System.Windows.Forms.Label lblPublicationYear;
        private System.Windows.Forms.TextBox txtPublicationYear;
        private System.Windows.Forms.Label lblEdition;
        private System.Windows.Forms.TextBox txtEdition;
        private System.Windows.Forms.Panel panelClassification;
        private System.Windows.Forms.Label lblClassification;
        private System.Windows.Forms.Label lblCategory;
        private System.Windows.Forms.ComboBox cmbCategory;
        private System.Windows.Forms.Label lblSubjectClassification;
        private System.Windows.Forms.TextBox txtSubjectClassification;
        private System.Windows.Forms.Label lblLanguage;
        private System.Windows.Forms.ComboBox cmbLanguage;
        private System.Windows.Forms.Panel panelPhysicalDescription;
        private System.Windows.Forms.Label lblPhysicalDesc;
        private System.Windows.Forms.Label lblNumberOfPages;
        private System.Windows.Forms.TextBox txtNumberOfPages;
        private System.Windows.Forms.Label lblPhysicalDescription;
        private System.Windows.Forms.TextBox txtPhysicalDescription;
        private System.Windows.Forms.Panel panelLocationCopies;
        private System.Windows.Forms.Label lblLocationCopies;
        private System.Windows.Forms.Label lblShelfLocation;
        private System.Windows.Forms.TextBox txtShelfLocation;
        private System.Windows.Forms.Label lblNumberOfCopies;
        private System.Windows.Forms.TextBox txtNumberOfCopies;
        private System.Windows.Forms.Button btnIncreaseCopies;
        private System.Windows.Forms.Button btnDecreaseCopies;
        private System.Windows.Forms.Panel panelBookCover;
        private System.Windows.Forms.Label lblBookCover;
        private System.Windows.Forms.Panel panelUploadArea;
        private System.Windows.Forms.PictureBox picBookCover;
        private System.Windows.Forms.Label lblUploadText;
        private System.Windows.Forms.Label lblFileInfo;
        private System.Windows.Forms.Panel panelBookType;
        private System.Windows.Forms.Label lblBookType;
        private System.Windows.Forms.Panel panelCirculationBookCard;
        private System.Windows.Forms.Label lblCirculationBookTitle;
        private System.Windows.Forms.Label lblCirculationBookDesc;
        private System.Windows.Forms.RadioButton radioCirculationBook;
        private System.Windows.Forms.Panel panelReferenceBookCard;
        private System.Windows.Forms.Label lblReferenceBookTitle;
        private System.Windows.Forms.Label lblReferenceBookDesc;
        private System.Windows.Forms.RadioButton radioReferenceBook;
        private System.Windows.Forms.Panel panelFooter;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnAddBook;
    }
}