namespace Project5LMS.Forms.Admin.Catalog
{
    partial class ThesisForm
    {
        private System.ComponentModel.IContainer components = null;
        private new System.Windows.Forms.Panel panelMain;
        private System.Windows.Forms.Label lblStudentName;
        private System.Windows.Forms.TextBox txtStudentName;
        private System.Windows.Forms.Label lblStudentID;
        private System.Windows.Forms.TextBox txtStudentID;
        private System.Windows.Forms.Label lblDegree;
        private System.Windows.Forms.TextBox txtDegree;
        private System.Windows.Forms.Label lblDepartment;
        private System.Windows.Forms.TextBox txtDepartment;
        private System.Windows.Forms.Label lblAdvisor;
        private System.Windows.Forms.TextBox txtAdvisor;
        private System.Windows.Forms.Label lblDefenseDate;
        private System.Windows.Forms.DateTimePicker dtpDefenseDate;
        private System.Windows.Forms.Label lblAbstract;
        private System.Windows.Forms.TextBox txtAbstract;
        private System.Windows.Forms.CheckBox chkIsRestricted;
        private new System.Windows.Forms.Button btnSave;
        private new System.Windows.Forms.Button btnCancel;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.panelMain = new System.Windows.Forms.Panel();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnSave = new System.Windows.Forms.Button();
            this.chkIsRestricted = new System.Windows.Forms.CheckBox();
            this.txtAbstract = new System.Windows.Forms.TextBox();
            this.lblAbstract = new System.Windows.Forms.Label();
            this.dtpDefenseDate = new System.Windows.Forms.DateTimePicker();
            this.lblDefenseDate = new System.Windows.Forms.Label();
            this.txtAdvisor = new System.Windows.Forms.TextBox();
            this.lblAdvisor = new System.Windows.Forms.Label();
            this.txtDepartment = new System.Windows.Forms.TextBox();
            this.lblDepartment = new System.Windows.Forms.Label();
            this.txtDegree = new System.Windows.Forms.TextBox();
            this.lblDegree = new System.Windows.Forms.Label();
            this.txtStudentID = new System.Windows.Forms.TextBox();
            this.lblStudentID = new System.Windows.Forms.Label();
            this.txtStudentName = new System.Windows.Forms.TextBox();
            this.lblStudentName = new System.Windows.Forms.Label();
            this.panelMain.SuspendLayout();
            this.SuspendLayout();
            this.panelMain.Controls.Add(this.btnCancel);
            this.panelMain.Controls.Add(this.btnSave);
            this.panelMain.Controls.Add(this.chkIsRestricted);
            this.panelMain.Controls.Add(this.txtAbstract);
            this.panelMain.Controls.Add(this.lblAbstract);
            this.panelMain.Controls.Add(this.dtpDefenseDate);
            this.panelMain.Controls.Add(this.lblDefenseDate);
            this.panelMain.Controls.Add(this.txtAdvisor);
            this.panelMain.Controls.Add(this.lblAdvisor);
            this.panelMain.Controls.Add(this.txtDepartment);
            this.panelMain.Controls.Add(this.lblDepartment);
            this.panelMain.Controls.Add(this.txtDegree);
            this.panelMain.Controls.Add(this.lblDegree);
            this.panelMain.Controls.Add(this.txtStudentID);
            this.panelMain.Controls.Add(this.lblStudentID);
            this.panelMain.Controls.Add(this.txtStudentName);
            this.panelMain.Controls.Add(this.lblStudentName);
            this.panelMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMain.Location = new System.Drawing.Point(0, 0);
            this.panelMain.Name = "panelMain";
            this.panelMain.Padding = new System.Windows.Forms.Padding(20);
            this.panelMain.Size = new System.Drawing.Size(500, 500);
            this.panelMain.TabIndex = 0;
            this.btnCancel.BackColor = System.Drawing.Color.Maroon;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.Location = new System.Drawing.Point(130, 404);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(100, 49);
            this.btnCancel.TabIndex = 16;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnSave.BackColor = System.Drawing.Color.Maroon;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.Location = new System.Drawing.Point(330, 404);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(100, 49);
            this.btnSave.TabIndex = 15;
            this.btnSave.Text = "Save";
            this.btnSave.UseVisualStyleBackColor = false;
            this.btnSave.Click += new System.EventHandler(this.BtnSave_Click);
            this.chkIsRestricted.AutoSize = true;
            this.chkIsRestricted.Location = new System.Drawing.Point(130, 340);
            this.chkIsRestricted.Name = "chkIsRestricted";
            this.chkIsRestricted.Size = new System.Drawing.Size(138, 20);
            this.chkIsRestricted.TabIndex = 14;
            this.chkIsRestricted.Text = "Restricted Access";
            this.chkIsRestricted.UseVisualStyleBackColor = true;
            this.txtAbstract.Location = new System.Drawing.Point(130, 257);
            this.txtAbstract.Multiline = true;
            this.txtAbstract.Name = "txtAbstract";
            this.txtAbstract.Size = new System.Drawing.Size(300, 60);
            this.txtAbstract.TabIndex = 13;
            this.lblAbstract.AutoSize = true;
            this.lblAbstract.Location = new System.Drawing.Point(20, 260);
            this.lblAbstract.Name = "lblAbstract";
            this.lblAbstract.Size = new System.Drawing.Size(59, 16);
            this.lblAbstract.TabIndex = 12;
            this.lblAbstract.Text = "Abstract:";
            this.dtpDefenseDate.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpDefenseDate.Location = new System.Drawing.Point(130, 217);
            this.dtpDefenseDate.Name = "dtpDefenseDate";
            this.dtpDefenseDate.Size = new System.Drawing.Size(300, 22);
            this.dtpDefenseDate.TabIndex = 11;
            this.lblDefenseDate.AutoSize = true;
            this.lblDefenseDate.Location = new System.Drawing.Point(20, 220);
            this.lblDefenseDate.Name = "lblDefenseDate";
            this.lblDefenseDate.Size = new System.Drawing.Size(93, 16);
            this.lblDefenseDate.TabIndex = 10;
            this.lblDefenseDate.Text = "Defense Date:";
            this.txtAdvisor.Location = new System.Drawing.Point(130, 177);
            this.txtAdvisor.Name = "txtAdvisor";
            this.txtAdvisor.Size = new System.Drawing.Size(300, 22);
            this.txtAdvisor.TabIndex = 9;
            this.lblAdvisor.AutoSize = true;
            this.lblAdvisor.Location = new System.Drawing.Point(20, 180);
            this.lblAdvisor.Name = "lblAdvisor";
            this.lblAdvisor.Size = new System.Drawing.Size(56, 16);
            this.lblAdvisor.TabIndex = 8;
            this.lblAdvisor.Text = "Advisor:";
            this.txtDepartment.Location = new System.Drawing.Point(130, 137);
            this.txtDepartment.Name = "txtDepartment";
            this.txtDepartment.Size = new System.Drawing.Size(300, 22);
            this.txtDepartment.TabIndex = 7;
            this.lblDepartment.AutoSize = true;
            this.lblDepartment.Location = new System.Drawing.Point(20, 140);
            this.lblDepartment.Name = "lblDepartment";
            this.lblDepartment.Size = new System.Drawing.Size(80, 16);
            this.lblDepartment.TabIndex = 6;
            this.lblDepartment.Text = "Department:";
            this.txtDegree.Location = new System.Drawing.Point(130, 97);
            this.txtDegree.Name = "txtDegree";
            this.txtDegree.Size = new System.Drawing.Size(300, 22);
            this.txtDegree.TabIndex = 5;
            this.lblDegree.AutoSize = true;
            this.lblDegree.Location = new System.Drawing.Point(20, 100);
            this.lblDegree.Name = "lblDegree";
            this.lblDegree.Size = new System.Drawing.Size(56, 16);
            this.lblDegree.TabIndex = 4;
            this.lblDegree.Text = "Degree:";
            this.txtStudentID.Location = new System.Drawing.Point(130, 57);
            this.txtStudentID.Name = "txtStudentID";
            this.txtStudentID.Size = new System.Drawing.Size(300, 22);
            this.txtStudentID.TabIndex = 3;
            this.lblStudentID.AutoSize = true;
            this.lblStudentID.Location = new System.Drawing.Point(20, 60);
            this.lblStudentID.Name = "lblStudentID";
            this.lblStudentID.Size = new System.Drawing.Size(71, 16);
            this.lblStudentID.TabIndex = 2;
            this.lblStudentID.Text = "Student ID:";
            this.txtStudentName.Location = new System.Drawing.Point(130, 17);
            this.txtStudentName.Name = "txtStudentName";
            this.txtStudentName.Size = new System.Drawing.Size(300, 22);
            this.txtStudentName.TabIndex = 1;
            this.lblStudentName.AutoSize = true;
            this.lblStudentName.Location = new System.Drawing.Point(20, 20);
            this.lblStudentName.Name = "lblStudentName";
            this.lblStudentName.Size = new System.Drawing.Size(95, 16);
            this.lblStudentName.TabIndex = 0;
            this.lblStudentName.Text = "Student Name:";
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(500, 500);
            this.Controls.Add(this.panelMain);
            this.Name = "ThesisForm";
            this.Text = "Add Thesis/Dissertation";
            this.panelMain.ResumeLayout(false);
            this.panelMain.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
    }
}