namespace Project5LMS.Forms.Admin.Dashboard
{
    partial class AdminDashboardForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.panelSidebar = new System.Windows.Forms.Panel();
            this.btnLogout = new System.Windows.Forms.Button();
            this.lblAdmin = new System.Windows.Forms.Label();
            this.panelSeparator = new System.Windows.Forms.Panel();
            this.btnSettings = new System.Windows.Forms.Button();
            this.btnSearch = new System.Windows.Forms.Button();
            this.btnReports = new System.Windows.Forms.Button();
            this.btnInventory = new System.Windows.Forms.Button();
            this.btnFines = new System.Windows.Forms.Button();
            this.btnReservations = new System.Windows.Forms.Button();
            this.btnCirculation = new System.Windows.Forms.Button();
            this.btnCatalog = new System.Windows.Forms.Button();
            this.btnMembers = new System.Windows.Forms.Button();
            this.btnUserManagement = new System.Windows.Forms.Button();
            this.btnDashboard = new System.Windows.Forms.Button();
            this.lblSubtitleSidebar = new System.Windows.Forms.Label();
            this.lblTitleSidebar = new System.Windows.Forms.Label();
            this.panelMainContent = new System.Windows.Forms.Panel();
            this.panelDashboardContainer = new System.Windows.Forms.Panel();
            this.panelPieChart = new System.Windows.Forms.Panel();
            this.lblPieChartTitle = new System.Windows.Forms.Label();
            this.panelRecentActivities = new System.Windows.Forms.Panel();
            this.lblRecentActivitiesTitle = new System.Windows.Forms.Label();
            this.panelActivitiesList = new System.Windows.Forms.Panel();
            this.panelBarChart = new System.Windows.Forms.Panel();
            this.lblBarChartTitle = new System.Windows.Forms.Label();
            this.panelMetrics = new System.Windows.Forms.Panel();
            this.panelMetricBooks = new System.Windows.Forms.Panel();
            this.lblBooksChange = new System.Windows.Forms.Label();
            this.lblBooksValue = new System.Windows.Forms.Label();
            this.lblBooksTitle = new System.Windows.Forms.Label();
            this.panelMetricMembers = new System.Windows.Forms.Panel();
            this.lblMembersChange = new System.Windows.Forms.Label();
            this.lblMembersValue = new System.Windows.Forms.Label();
            this.lblMembersTitle = new System.Windows.Forms.Label();
            this.panelMetricBorrowed = new System.Windows.Forms.Panel();
            this.lblBorrowedChange = new System.Windows.Forms.Label();
            this.lblBorrowedValue = new System.Windows.Forms.Label();
            this.lblBorrowedTitle = new System.Windows.Forms.Label();
            this.panelMetricFines = new System.Windows.Forms.Panel();
            this.lblFinesChange = new System.Windows.Forms.Label();
            this.lblFinesValue = new System.Windows.Forms.Label();
            this.lblFinesTitle = new System.Windows.Forms.Label();
            this.panelMetricOverdue = new System.Windows.Forms.Panel();
            this.lblOverdueChange = new System.Windows.Forms.Label();
            this.lblOverdueValue = new System.Windows.Forms.Label();
            this.lblOverdueTitle = new System.Windows.Forms.Label();
            this.panelMetricReservations = new System.Windows.Forms.Panel();
            this.lblReservationsChange = new System.Windows.Forms.Label();
            this.lblReservationsValue = new System.Windows.Forms.Label();
            this.lblReservationsTitle = new System.Windows.Forms.Label();
            this.panelHeader = new System.Windows.Forms.Panel();
            this.lblSubtitle = new System.Windows.Forms.Label();
            this.lblTitle = new System.Windows.Forms.Label();
            this.panelSidebar.SuspendLayout();
            this.panelMainContent.SuspendLayout();
            this.panelDashboardContainer.SuspendLayout();
            this.panelPieChart.SuspendLayout();
            this.panelRecentActivities.SuspendLayout();
            this.panelBarChart.SuspendLayout();
            this.panelMetrics.SuspendLayout();
            this.panelMetricBooks.SuspendLayout();
            this.panelMetricMembers.SuspendLayout();
            this.panelMetricBorrowed.SuspendLayout();
            this.panelMetricFines.SuspendLayout();
            this.panelMetricOverdue.SuspendLayout();
            this.panelMetricReservations.SuspendLayout();
            this.panelHeader.SuspendLayout();
            this.SuspendLayout();
            this.panelSidebar.BackColor = System.Drawing.Color.Maroon;
            this.panelSidebar.Controls.Add(this.btnLogout);
            this.panelSidebar.Controls.Add(this.lblAdmin);
            this.panelSidebar.Controls.Add(this.panelSeparator);
            this.panelSidebar.Controls.Add(this.btnSettings);
            this.panelSidebar.Controls.Add(this.btnSearch);
            this.panelSidebar.Controls.Add(this.btnReports);
            this.panelSidebar.Controls.Add(this.btnInventory);
            this.panelSidebar.Controls.Add(this.btnFines);
            this.panelSidebar.Controls.Add(this.btnReservations);
            this.panelSidebar.Controls.Add(this.btnCirculation);
            this.panelSidebar.Controls.Add(this.btnCatalog);
            this.panelSidebar.Controls.Add(this.btnMembers);
            this.panelSidebar.Controls.Add(this.btnUserManagement);
            this.panelSidebar.Controls.Add(this.btnDashboard);
            this.panelSidebar.Controls.Add(this.lblSubtitleSidebar);
            this.panelSidebar.Controls.Add(this.lblTitleSidebar);
            this.panelSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelSidebar.Location = new System.Drawing.Point(0, 0);
            this.panelSidebar.Margin = new System.Windows.Forms.Padding(4);
            this.panelSidebar.Name = "panelSidebar";
            this.panelSidebar.Padding = new System.Windows.Forms.Padding(20, 30, 20, 30);
            this.panelSidebar.Size = new System.Drawing.Size(280, 985);
            this.panelSidebar.TabIndex = 0;
            this.btnLogout.BackColor = System.Drawing.Color.Maroon;
            this.btnLogout.FlatAppearance.BorderSize = 0;
            this.btnLogout.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLogout.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLogout.ForeColor = System.Drawing.Color.White;
            this.btnLogout.Location = new System.Drawing.Point(20, 921);
            this.btnLogout.Margin = new System.Windows.Forms.Padding(4);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.Size = new System.Drawing.Size(240, 46);
            this.btnLogout.TabIndex = 14;
            this.btnLogout.Text = "🚪 Logout";
            this.btnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.UseVisualStyleBackColor = false;
            this.btnLogout.Click += new System.EventHandler(this.btnLogout_Click);
            this.lblAdmin.AutoSize = true;
            this.lblAdmin.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAdmin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.lblAdmin.Location = new System.Drawing.Point(20, 850);
            this.lblAdmin.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblAdmin.Name = "lblAdmin";
            this.lblAdmin.Size = new System.Drawing.Size(66, 23);
            this.lblAdmin.TabIndex = 13;
            this.lblAdmin.Text = "ADMIN";
            this.panelSeparator.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.panelSeparator.Location = new System.Drawing.Point(20, 830);
            this.panelSeparator.Margin = new System.Windows.Forms.Padding(4);
            this.panelSeparator.Name = "panelSeparator";
            this.panelSeparator.Size = new System.Drawing.Size(240, 1);
            this.panelSeparator.TabIndex = 12;
            this.btnSettings.BackColor = System.Drawing.Color.Maroon;
            this.btnSettings.FlatAppearance.BorderSize = 0;
            this.btnSettings.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSettings.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSettings.ForeColor = System.Drawing.Color.White;
            this.btnSettings.Location = new System.Drawing.Point(20, 650);
            this.btnSettings.Margin = new System.Windows.Forms.Padding(4);
            this.btnSettings.Name = "btnSettings";
            this.btnSettings.Size = new System.Drawing.Size(240, 50);
            this.btnSettings.TabIndex = 11;
            this.btnSettings.Text = "⚙️ System Settings";
            this.btnSettings.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSettings.UseVisualStyleBackColor = false;
            this.btnSettings.Click += new System.EventHandler(this.btnSettings_Click);
            this.btnSearch.BackColor = System.Drawing.Color.Maroon;
            this.btnSearch.FlatAppearance.BorderSize = 0;
            this.btnSearch.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.Location = new System.Drawing.Point(20, 601);
            this.btnSearch.Margin = new System.Windows.Forms.Padding(4);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(240, 50);
            this.btnSearch.TabIndex = 10;
            this.btnSearch.Text = "🔍 Search";
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.UseVisualStyleBackColor = false;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            this.btnReports.BackColor = System.Drawing.Color.Maroon;
            this.btnReports.FlatAppearance.BorderSize = 0;
            this.btnReports.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReports.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReports.ForeColor = System.Drawing.Color.White;
            this.btnReports.Location = new System.Drawing.Point(20, 550);
            this.btnReports.Margin = new System.Windows.Forms.Padding(4);
            this.btnReports.Name = "btnReports";
            this.btnReports.Size = new System.Drawing.Size(240, 50);
            this.btnReports.TabIndex = 9;
            this.btnReports.Text = "📄 Reports";
            this.btnReports.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReports.UseVisualStyleBackColor = false;
            this.btnReports.Click += new System.EventHandler(this.btnReports_Click);
            this.btnInventory.BackColor = System.Drawing.Color.Maroon;
            this.btnInventory.FlatAppearance.BorderSize = 0;
            this.btnInventory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnInventory.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInventory.ForeColor = System.Drawing.Color.White;
            this.btnInventory.Location = new System.Drawing.Point(20, 500);
            this.btnInventory.Margin = new System.Windows.Forms.Padding(4);
            this.btnInventory.Name = "btnInventory";
            this.btnInventory.Size = new System.Drawing.Size(240, 50);
            this.btnInventory.TabIndex = 8;
            this.btnInventory.Text = "📦 Inventory";
            this.btnInventory.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInventory.UseVisualStyleBackColor = false;
            this.btnInventory.Click += new System.EventHandler(this.btnInventory_Click);
            this.btnFines.BackColor = System.Drawing.Color.Maroon;
            this.btnFines.FlatAppearance.BorderSize = 0;
            this.btnFines.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFines.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFines.ForeColor = System.Drawing.Color.White;
            this.btnFines.Location = new System.Drawing.Point(20, 450);
            this.btnFines.Margin = new System.Windows.Forms.Padding(4);
            this.btnFines.Name = "btnFines";
            this.btnFines.Size = new System.Drawing.Size(240, 50);
            this.btnFines.TabIndex = 7;
            this.btnFines.Text = "💰 Fines";
            this.btnFines.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFines.UseVisualStyleBackColor = false;
            this.btnFines.Click += new System.EventHandler(this.btnFines_Click);
            this.btnReservations.BackColor = System.Drawing.Color.Maroon;
            this.btnReservations.FlatAppearance.BorderSize = 0;
            this.btnReservations.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReservations.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReservations.ForeColor = System.Drawing.Color.White;
            this.btnReservations.Location = new System.Drawing.Point(20, 400);
            this.btnReservations.Margin = new System.Windows.Forms.Padding(4);
            this.btnReservations.Name = "btnReservations";
            this.btnReservations.Size = new System.Drawing.Size(240, 50);
            this.btnReservations.TabIndex = 6;
            this.btnReservations.Text = "📅 Reservations";
            this.btnReservations.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReservations.UseVisualStyleBackColor = false;
            this.btnReservations.Click += new System.EventHandler(this.btnReservations_Click);
            this.btnCirculation.BackColor = System.Drawing.Color.Maroon;
            this.btnCirculation.FlatAppearance.BorderSize = 0;
            this.btnCirculation.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCirculation.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCirculation.ForeColor = System.Drawing.Color.White;
            this.btnCirculation.Location = new System.Drawing.Point(20, 350);
            this.btnCirculation.Margin = new System.Windows.Forms.Padding(4);
            this.btnCirculation.Name = "btnCirculation";
            this.btnCirculation.Size = new System.Drawing.Size(240, 50);
            this.btnCirculation.TabIndex = 5;
            this.btnCirculation.Text = "🔄 Circulation";
            this.btnCirculation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCirculation.UseVisualStyleBackColor = false;
            this.btnCirculation.Click += new System.EventHandler(this.btnCirculation_Click);
            this.btnCatalog.BackColor = System.Drawing.Color.Maroon;
            this.btnCatalog.FlatAppearance.BorderSize = 0;
            this.btnCatalog.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCatalog.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCatalog.ForeColor = System.Drawing.Color.White;
            this.btnCatalog.Location = new System.Drawing.Point(20, 300);
            this.btnCatalog.Margin = new System.Windows.Forms.Padding(4);
            this.btnCatalog.Name = "btnCatalog";
            this.btnCatalog.Size = new System.Drawing.Size(240, 50);
            this.btnCatalog.TabIndex = 4;
            this.btnCatalog.Text = "📚  Catalog";
            this.btnCatalog.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCatalog.UseVisualStyleBackColor = false;
            this.btnCatalog.Click += new System.EventHandler(this.btnCatalog_Click);
            this.btnMembers.BackColor = System.Drawing.Color.Maroon;
            this.btnMembers.FlatAppearance.BorderSize = 0;
            this.btnMembers.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMembers.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMembers.ForeColor = System.Drawing.Color.White;
            this.btnMembers.Location = new System.Drawing.Point(20, 250);
            this.btnMembers.Margin = new System.Windows.Forms.Padding(4);
            this.btnMembers.Name = "btnMembers";
            this.btnMembers.Size = new System.Drawing.Size(240, 50);
            this.btnMembers.TabIndex = 3;
            this.btnMembers.Text = "👥  Members";
            this.btnMembers.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMembers.UseVisualStyleBackColor = false;
            this.btnMembers.Click += new System.EventHandler(this.btnMembers_Click);
            this.btnUserManagement.BackColor = System.Drawing.Color.Maroon;
            this.btnUserManagement.FlatAppearance.BorderSize = 0;
            this.btnUserManagement.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnUserManagement.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUserManagement.ForeColor = System.Drawing.Color.White;
            this.btnUserManagement.Location = new System.Drawing.Point(20, 199);
            this.btnUserManagement.Margin = new System.Windows.Forms.Padding(4);
            this.btnUserManagement.Name = "btnUserManagement";
            this.btnUserManagement.Size = new System.Drawing.Size(240, 50);
            this.btnUserManagement.TabIndex = 2;
            this.btnUserManagement.Text = "👤 User Management";
            this.btnUserManagement.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUserManagement.UseVisualStyleBackColor = false;
            this.btnUserManagement.Click += new System.EventHandler(this.btnUserManagement_Click);
            this.btnDashboard.BackColor = System.Drawing.Color.Maroon;
            this.btnDashboard.FlatAppearance.BorderSize = 0;
            this.btnDashboard.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDashboard.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.Location = new System.Drawing.Point(20, 150);
            this.btnDashboard.Margin = new System.Windows.Forms.Padding(4);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.Size = new System.Drawing.Size(240, 50);
            this.btnDashboard.TabIndex = 1;
            this.btnDashboard.Text = "📊 Dashboard";
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.UseVisualStyleBackColor = false;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click);
            this.lblSubtitleSidebar.AutoSize = true;
            this.lblSubtitleSidebar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSubtitleSidebar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.lblSubtitleSidebar.Location = new System.Drawing.Point(27, 62);
            this.lblSubtitleSidebar.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblSubtitleSidebar.Name = "lblSubtitleSidebar";
            this.lblSubtitleSidebar.Size = new System.Drawing.Size(171, 23);
            this.lblSubtitleSidebar.TabIndex = 1;
            this.lblSubtitleSidebar.Text = "Management System";
            this.lblTitleSidebar.AutoSize = true;
            this.lblTitleSidebar.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitleSidebar.ForeColor = System.Drawing.SystemColors.Window;
            this.lblTitleSidebar.Location = new System.Drawing.Point(24, 21);
            this.lblTitleSidebar.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblTitleSidebar.Name = "lblTitleSidebar";
            this.lblTitleSidebar.Size = new System.Drawing.Size(177, 41);
            this.lblTitleSidebar.TabIndex = 0;
            this.lblTitleSidebar.Text = "UM Library";
            this.panelMainContent.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(250)))), ((int)(((byte)(250)))));
            this.panelMainContent.Controls.Add(this.panelDashboardContainer);
            this.panelMainContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMainContent.Location = new System.Drawing.Point(280, 0);
            this.panelMainContent.Margin = new System.Windows.Forms.Padding(0);
            this.panelMainContent.Name = "panelMainContent";
            this.panelMainContent.Size = new System.Drawing.Size(1316, 985);
            this.panelMainContent.TabIndex = 1;
            this.panelDashboardContainer.AutoScroll = true;
            this.panelDashboardContainer.BackColor = System.Drawing.Color.WhiteSmoke;
            this.panelDashboardContainer.Controls.Add(this.panelPieChart);
            this.panelDashboardContainer.Controls.Add(this.panelRecentActivities);
            this.panelDashboardContainer.Controls.Add(this.panelBarChart);
            this.panelDashboardContainer.Controls.Add(this.panelMetrics);
            this.panelDashboardContainer.Controls.Add(this.panelHeader);
            this.panelDashboardContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelDashboardContainer.Location = new System.Drawing.Point(0, 0);
            this.panelDashboardContainer.Margin = new System.Windows.Forms.Padding(0);
            this.panelDashboardContainer.Name = "panelDashboardContainer";
            this.panelDashboardContainer.Padding = new System.Windows.Forms.Padding(20);
            this.panelDashboardContainer.Size = new System.Drawing.Size(1316, 985);
            this.panelDashboardContainer.TabIndex = 0;
            this.panelPieChart.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelPieChart.BackColor = System.Drawing.Color.White;
            this.panelPieChart.Controls.Add(this.lblPieChartTitle);
            this.panelPieChart.Location = new System.Drawing.Point(665, 400);
            this.panelPieChart.Margin = new System.Windows.Forms.Padding(11, 0, 0, 0);
            this.panelPieChart.Name = "panelPieChart";
            this.panelPieChart.Padding = new System.Windows.Forms.Padding(20);
            this.panelPieChart.Size = new System.Drawing.Size(629, 300);
            this.panelPieChart.TabIndex = 1;
            this.panelPieChart.Paint += new System.Windows.Forms.PaintEventHandler(this.panelPieChart_Paint);
            this.lblPieChartTitle.AutoSize = true;
            this.lblPieChartTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPieChartTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPieChartTitle.Location = new System.Drawing.Point(20, 20);
            this.lblPieChartTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblPieChartTitle.Name = "lblPieChartTitle";
            this.lblPieChartTitle.Size = new System.Drawing.Size(229, 32);
            this.lblPieChartTitle.TabIndex = 0;
            this.lblPieChartTitle.Text = "Books by Category";
            this.panelRecentActivities.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelRecentActivities.BackColor = System.Drawing.Color.White;
            this.panelRecentActivities.Controls.Add(this.lblRecentActivitiesTitle);
            this.panelRecentActivities.Controls.Add(this.panelActivitiesList);
            this.panelRecentActivities.Location = new System.Drawing.Point(20, 704);
            this.panelRecentActivities.Margin = new System.Windows.Forms.Padding(0, 10, 0, 20);
            this.panelRecentActivities.Name = "panelRecentActivities";
            this.panelRecentActivities.Padding = new System.Windows.Forms.Padding(20);
            this.panelRecentActivities.Size = new System.Drawing.Size(1276, 261);
            this.panelRecentActivities.TabIndex = 3;
            this.panelRecentActivities.Paint += new System.Windows.Forms.PaintEventHandler(this.panelRecentActivities_Paint);
            this.lblRecentActivitiesTitle.AutoSize = true;
            this.lblRecentActivitiesTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblRecentActivitiesTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblRecentActivitiesTitle.Location = new System.Drawing.Point(20, 20);
            this.lblRecentActivitiesTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblRecentActivitiesTitle.Name = "lblRecentActivitiesTitle";
            this.lblRecentActivitiesTitle.Size = new System.Drawing.Size(203, 32);
            this.lblRecentActivitiesTitle.TabIndex = 0;
            this.lblRecentActivitiesTitle.Text = "Recent Activities";
            this.panelActivitiesList.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelActivitiesList.AutoScroll = true;
            this.panelActivitiesList.Location = new System.Drawing.Point(20, 60);
            this.panelActivitiesList.Margin = new System.Windows.Forms.Padding(0);
            this.panelActivitiesList.Name = "panelActivitiesList";
            this.panelActivitiesList.Size = new System.Drawing.Size(1236, 181);
            this.panelActivitiesList.TabIndex = 1;
            this.panelBarChart.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelBarChart.BackColor = System.Drawing.Color.White;
            this.panelBarChart.Controls.Add(this.lblBarChartTitle);
            this.panelBarChart.Location = new System.Drawing.Point(19, 400);
            this.panelBarChart.Margin = new System.Windows.Forms.Padding(0, 0, 11, 0);
            this.panelBarChart.Name = "panelBarChart";
            this.panelBarChart.Padding = new System.Windows.Forms.Padding(20);
            this.panelBarChart.Size = new System.Drawing.Size(625, 300);
            this.panelBarChart.TabIndex = 0;
            this.panelBarChart.Paint += new System.Windows.Forms.PaintEventHandler(this.panelBarChart_Paint);
            this.lblBarChartTitle.AutoSize = true;
            this.lblBarChartTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBarChartTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBarChartTitle.Location = new System.Drawing.Point(20, 20);
            this.lblBarChartTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBarChartTitle.Name = "lblBarChartTitle";
            this.lblBarChartTitle.Size = new System.Drawing.Size(307, 32);
            this.lblBarChartTitle.TabIndex = 0;
            this.lblBarChartTitle.Text = "Weekly Borrowing Trends";
            this.panelMetrics.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelMetrics.Controls.Add(this.panelMetricBooks);
            this.panelMetrics.Controls.Add(this.panelMetricMembers);
            this.panelMetrics.Controls.Add(this.panelMetricBorrowed);
            this.panelMetrics.Controls.Add(this.panelMetricFines);
            this.panelMetrics.Controls.Add(this.panelMetricOverdue);
            this.panelMetrics.Controls.Add(this.panelMetricReservations);
            this.panelMetrics.Location = new System.Drawing.Point(20, 0);
            this.panelMetrics.Margin = new System.Windows.Forms.Padding(0, 10, 20, 10);
            this.panelMetrics.Name = "panelMetrics";
            this.panelMetrics.Size = new System.Drawing.Size(1276, 400);
            this.panelMetrics.TabIndex = 1;
            this.panelMetricBooks.BackColor = System.Drawing.Color.White;
            this.panelMetricBooks.Controls.Add(this.lblBooksChange);
            this.panelMetricBooks.Controls.Add(this.lblBooksValue);
            this.panelMetricBooks.Controls.Add(this.lblBooksTitle);
            this.panelMetricBooks.Location = new System.Drawing.Point(0, 0);
            this.panelMetricBooks.Margin = new System.Windows.Forms.Padding(0, 0, 5, 0);
            this.panelMetricBooks.Name = "panelMetricBooks";
            this.panelMetricBooks.Padding = new System.Windows.Forms.Padding(20);
            this.panelMetricBooks.Size = new System.Drawing.Size(423, 190);
            this.panelMetricBooks.TabIndex = 0;
            this.lblBooksChange.AutoSize = true;
            this.lblBooksChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBooksChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblBooksChange.Location = new System.Drawing.Point(20, 140);
            this.lblBooksChange.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBooksChange.Name = "lblBooksChange";
            this.lblBooksChange.Size = new System.Drawing.Size(137, 23);
            this.lblBooksChange.TabIndex = 3;
            this.lblBooksChange.Text = "+125 this month";
            this.lblBooksValue.AutoSize = true;
            this.lblBooksValue.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBooksValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBooksValue.Location = new System.Drawing.Point(20, 80);
            this.lblBooksValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBooksValue.Name = "lblBooksValue";
            this.lblBooksValue.Size = new System.Drawing.Size(149, 54);
            this.lblBooksValue.TabIndex = 2;
            this.lblBooksValue.Text = "12,458";
            this.lblBooksTitle.AutoSize = true;
            this.lblBooksTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBooksTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblBooksTitle.Location = new System.Drawing.Point(20, 20);
            this.lblBooksTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBooksTitle.Name = "lblBooksTitle";
            this.lblBooksTitle.Size = new System.Drawing.Size(144, 28);
            this.lblBooksTitle.TabIndex = 1;
            this.lblBooksTitle.Text = "📚 Total Books";
            this.panelMetricMembers.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelMetricMembers.BackColor = System.Drawing.Color.White;
            this.panelMetricMembers.Controls.Add(this.lblMembersChange);
            this.panelMetricMembers.Controls.Add(this.lblMembersValue);
            this.panelMetricMembers.Controls.Add(this.lblMembersTitle);
            this.panelMetricMembers.Location = new System.Drawing.Point(428, 0);
            this.panelMetricMembers.Margin = new System.Windows.Forms.Padding(5, 0, 5, 0);
            this.panelMetricMembers.Name = "panelMetricMembers";
            this.panelMetricMembers.Padding = new System.Windows.Forms.Padding(20);
            this.panelMetricMembers.Size = new System.Drawing.Size(419, 190);
            this.panelMetricMembers.TabIndex = 1;
            this.lblMembersChange.AutoSize = true;
            this.lblMembersChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMembersChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblMembersChange.Location = new System.Drawing.Point(20, 140);
            this.lblMembersChange.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblMembersChange.Name = "lblMembersChange";
            this.lblMembersChange.Size = new System.Drawing.Size(115, 23);
            this.lblMembersChange.TabIndex = 3;
            this.lblMembersChange.Text = "+52 this week";
            this.lblMembersValue.AutoSize = true;
            this.lblMembersValue.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMembersValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblMembersValue.Location = new System.Drawing.Point(20, 80);
            this.lblMembersValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblMembersValue.Name = "lblMembersValue";
            this.lblMembersValue.Size = new System.Drawing.Size(126, 54);
            this.lblMembersValue.TabIndex = 2;
            this.lblMembersValue.Text = "3,247";
            this.lblMembersTitle.AutoSize = true;
            this.lblMembersTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMembersTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblMembersTitle.Location = new System.Drawing.Point(20, 20);
            this.lblMembersTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblMembersTitle.Name = "lblMembersTitle";
            this.lblMembersTitle.Size = new System.Drawing.Size(185, 28);
            this.lblMembersTitle.TabIndex = 1;
            this.lblMembersTitle.Text = "👥 Active Members";
            this.panelMetricBorrowed.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelMetricBorrowed.BackColor = System.Drawing.Color.White;
            this.panelMetricBorrowed.Controls.Add(this.lblBorrowedChange);
            this.panelMetricBorrowed.Controls.Add(this.lblBorrowedValue);
            this.panelMetricBorrowed.Controls.Add(this.lblBorrowedTitle);
            this.panelMetricBorrowed.Location = new System.Drawing.Point(856, 0);
            this.panelMetricBorrowed.Margin = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.panelMetricBorrowed.Name = "panelMetricBorrowed";
            this.panelMetricBorrowed.Padding = new System.Windows.Forms.Padding(20);
            this.panelMetricBorrowed.Size = new System.Drawing.Size(420, 190);
            this.panelMetricBorrowed.TabIndex = 2;
            this.lblBorrowedChange.AutoSize = true;
            this.lblBorrowedChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBorrowedChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblBorrowedChange.Location = new System.Drawing.Point(20, 140);
            this.lblBorrowedChange.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBorrowedChange.Name = "lblBorrowedChange";
            this.lblBorrowedChange.Size = new System.Drawing.Size(88, 23);
            this.lblBorrowedChange.TabIndex = 3;
            this.lblBorrowedChange.Text = "+89 today";
            this.lblBorrowedValue.AutoSize = true;
            this.lblBorrowedValue.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBorrowedValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBorrowedValue.Location = new System.Drawing.Point(20, 80);
            this.lblBorrowedValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBorrowedValue.Name = "lblBorrowedValue";
            this.lblBorrowedValue.Size = new System.Drawing.Size(126, 54);
            this.lblBorrowedValue.TabIndex = 2;
            this.lblBorrowedValue.Text = "1,834";
            this.lblBorrowedTitle.AutoSize = true;
            this.lblBorrowedTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBorrowedTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblBorrowedTitle.Location = new System.Drawing.Point(20, 20);
            this.lblBorrowedTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblBorrowedTitle.Name = "lblBorrowedTitle";
            this.lblBorrowedTitle.Size = new System.Drawing.Size(187, 28);
            this.lblBorrowedTitle.TabIndex = 1;
            this.lblBorrowedTitle.Text = "📖 Books Borrowed";
            this.panelMetricFines.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelMetricFines.BackColor = System.Drawing.Color.White;
            this.panelMetricFines.Controls.Add(this.lblFinesChange);
            this.panelMetricFines.Controls.Add(this.lblFinesValue);
            this.panelMetricFines.Controls.Add(this.lblFinesTitle);
            this.panelMetricFines.Location = new System.Drawing.Point(0, 196);
            this.panelMetricFines.Margin = new System.Windows.Forms.Padding(5, 20, 5, 0);
            this.panelMetricFines.Name = "panelMetricFines";
            this.panelMetricFines.Padding = new System.Windows.Forms.Padding(20);
            this.panelMetricFines.Size = new System.Drawing.Size(419, 190);
            this.panelMetricFines.TabIndex = 4;
            this.lblFinesChange.AutoSize = true;
            this.lblFinesChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFinesChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblFinesChange.Location = new System.Drawing.Point(20, 140);
            this.lblFinesChange.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblFinesChange.Name = "lblFinesChange";
            this.lblFinesChange.Size = new System.Drawing.Size(167, 23);
            this.lblFinesChange.TabIndex = 3;
            this.lblFinesChange.Text = "$185 collected today";
            this.lblFinesValue.AutoSize = true;
            this.lblFinesValue.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFinesValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblFinesValue.Location = new System.Drawing.Point(20, 80);
            this.lblFinesValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblFinesValue.Name = "lblFinesValue";
            this.lblFinesValue.Size = new System.Drawing.Size(149, 54);
            this.lblFinesValue.TabIndex = 2;
            this.lblFinesValue.Text = "$2,458";
            this.lblFinesTitle.AutoSize = true;
            this.lblFinesTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblFinesTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblFinesTitle.Location = new System.Drawing.Point(20, 20);
            this.lblFinesTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblFinesTitle.Name = "lblFinesTitle";
            this.lblFinesTitle.Size = new System.Drawing.Size(164, 28);
            this.lblFinesTitle.TabIndex = 1;
            this.lblFinesTitle.Text = "💰 Pending Fines";
            this.panelMetricOverdue.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelMetricOverdue.BackColor = System.Drawing.Color.White;
            this.panelMetricOverdue.Controls.Add(this.lblOverdueChange);
            this.panelMetricOverdue.Controls.Add(this.lblOverdueValue);
            this.panelMetricOverdue.Controls.Add(this.lblOverdueTitle);
            this.panelMetricOverdue.Location = new System.Drawing.Point(428, 196);
            this.panelMetricOverdue.Margin = new System.Windows.Forms.Padding(0, 20, 5, 0);
            this.panelMetricOverdue.Name = "panelMetricOverdue";
            this.panelMetricOverdue.Padding = new System.Windows.Forms.Padding(20);
            this.panelMetricOverdue.Size = new System.Drawing.Size(419, 190);
            this.panelMetricOverdue.TabIndex = 3;
            this.lblOverdueChange.AutoSize = true;
            this.lblOverdueChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOverdueChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblOverdueChange.Location = new System.Drawing.Point(20, 140);
            this.lblOverdueChange.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOverdueChange.Name = "lblOverdueChange";
            this.lblOverdueChange.Size = new System.Drawing.Size(150, 23);
            this.lblOverdueChange.TabIndex = 3;
            this.lblOverdueChange.Text = "-15 from last week";
            this.lblOverdueValue.AutoSize = true;
            this.lblOverdueValue.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOverdueValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblOverdueValue.Location = new System.Drawing.Point(20, 80);
            this.lblOverdueValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOverdueValue.Name = "lblOverdueValue";
            this.lblOverdueValue.Size = new System.Drawing.Size(92, 54);
            this.lblOverdueValue.TabIndex = 2;
            this.lblOverdueValue.Text = "127";
            this.lblOverdueTitle.AutoSize = true;
            this.lblOverdueTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOverdueTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblOverdueTitle.Location = new System.Drawing.Point(20, 20);
            this.lblOverdueTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblOverdueTitle.Name = "lblOverdueTitle";
            this.lblOverdueTitle.Size = new System.Drawing.Size(177, 28);
            this.lblOverdueTitle.TabIndex = 1;
            this.lblOverdueTitle.Text = "⚠️ Overdue Books";
            this.panelMetricReservations.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelMetricReservations.BackColor = System.Drawing.Color.White;
            this.panelMetricReservations.Controls.Add(this.lblReservationsChange);
            this.panelMetricReservations.Controls.Add(this.lblReservationsValue);
            this.panelMetricReservations.Controls.Add(this.lblReservationsTitle);
            this.panelMetricReservations.Location = new System.Drawing.Point(856, 196);
            this.panelMetricReservations.Margin = new System.Windows.Forms.Padding(5, 20, 0, 0);
            this.panelMetricReservations.Name = "panelMetricReservations";
            this.panelMetricReservations.Padding = new System.Windows.Forms.Padding(20);
            this.panelMetricReservations.Size = new System.Drawing.Size(420, 190);
            this.panelMetricReservations.TabIndex = 5;
            this.lblReservationsChange.AutoSize = true;
            this.lblReservationsChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblReservationsChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblReservationsChange.Location = new System.Drawing.Point(20, 140);
            this.lblReservationsChange.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblReservationsChange.Name = "lblReservationsChange";
            this.lblReservationsChange.Size = new System.Drawing.Size(96, 23);
            this.lblReservationsChange.TabIndex = 3;
            this.lblReservationsChange.Text = "18 pending";
            this.lblReservationsValue.AutoSize = true;
            this.lblReservationsValue.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblReservationsValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblReservationsValue.Location = new System.Drawing.Point(20, 80);
            this.lblReservationsValue.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblReservationsValue.Name = "lblReservationsValue";
            this.lblReservationsValue.Size = new System.Drawing.Size(92, 54);
            this.lblReservationsValue.TabIndex = 2;
            this.lblReservationsValue.Text = "245";
            this.lblReservationsTitle.AutoSize = true;
            this.lblReservationsTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblReservationsTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblReservationsTitle.Location = new System.Drawing.Point(20, 20);
            this.lblReservationsTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblReservationsTitle.Name = "lblReservationsTitle";
            this.lblReservationsTitle.Size = new System.Drawing.Size(153, 28);
            this.lblReservationsTitle.TabIndex = 1;
            this.lblReservationsTitle.Text = "📅 Reservations";
            this.panelHeader.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelHeader.Controls.Add(this.lblSubtitle);
            this.panelHeader.Controls.Add(this.lblTitle);
            this.panelHeader.Location = new System.Drawing.Point(20, 20);
            this.panelHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Size = new System.Drawing.Size(1276, 130);
            this.panelHeader.TabIndex = 0;
            this.lblSubtitle.AutoSize = true;
            this.lblSubtitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblSubtitle.Location = new System.Drawing.Point(0, 60);
            this.lblSubtitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblSubtitle.Name = "lblSubtitle";
            this.lblSubtitle.Size = new System.Drawing.Size(550, 28);
            this.lblSubtitle.TabIndex = 1;
            this.lblSubtitle.Text = "Welcome back! Here\'s what\'s happening in your library today.";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(487, 62);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Dashboard Overview";
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1596, 985);
            this.Controls.Add(this.panelMainContent);
            this.Controls.Add(this.panelSidebar);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "AdminDashboardForm";
            this.Text = "LibraryMS - Management System";
            this.Load += new System.EventHandler(this.AdminDashboardForm_Load);
            this.panelSidebar.ResumeLayout(false);
            this.panelSidebar.PerformLayout();
            this.panelMainContent.ResumeLayout(false);
            this.panelDashboardContainer.ResumeLayout(false);
            this.panelPieChart.ResumeLayout(false);
            this.panelPieChart.PerformLayout();
            this.panelRecentActivities.ResumeLayout(false);
            this.panelRecentActivities.PerformLayout();
            this.panelBarChart.ResumeLayout(false);
            this.panelBarChart.PerformLayout();
            this.panelMetrics.ResumeLayout(false);
            this.panelMetricBooks.ResumeLayout(false);
            this.panelMetricBooks.PerformLayout();
            this.panelMetricMembers.ResumeLayout(false);
            this.panelMetricMembers.PerformLayout();
            this.panelMetricBorrowed.ResumeLayout(false);
            this.panelMetricBorrowed.PerformLayout();
            this.panelMetricFines.ResumeLayout(false);
            this.panelMetricFines.PerformLayout();
            this.panelMetricOverdue.ResumeLayout(false);
            this.panelMetricOverdue.PerformLayout();
            this.panelMetricReservations.ResumeLayout(false);
            this.panelMetricReservations.PerformLayout();
            this.panelHeader.ResumeLayout(false);
            this.panelHeader.PerformLayout();
            this.ResumeLayout(false);

        }
        #endregion
        private System.Windows.Forms.Panel panelSidebar;
        private System.Windows.Forms.Label lblTitleSidebar;
        private System.Windows.Forms.Label lblSubtitleSidebar;
        private System.Windows.Forms.Button btnDashboard;
        private System.Windows.Forms.Button btnUserManagement;
        private System.Windows.Forms.Button btnMembers;
        private System.Windows.Forms.Button btnCatalog;
        private System.Windows.Forms.Button btnCirculation;
        private System.Windows.Forms.Button btnReservations;
        private System.Windows.Forms.Button btnFines;
        private System.Windows.Forms.Button btnInventory;
        private System.Windows.Forms.Button btnReports;
        private System.Windows.Forms.Button btnSearch;
        private System.Windows.Forms.Button btnSettings;
        private System.Windows.Forms.Panel panelSeparator;
        private System.Windows.Forms.Label lblAdmin;
        private System.Windows.Forms.Button btnLogout;
        private System.Windows.Forms.Panel panelMainContent;
        private System.Windows.Forms.Panel panelDashboardContainer;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblSubtitle;
        private System.Windows.Forms.Panel panelMetrics;
        private System.Windows.Forms.Panel panelMetricBooks;
        private System.Windows.Forms.Label lblBooksTitle;
        private System.Windows.Forms.Label lblBooksValue;
        private System.Windows.Forms.Label lblBooksChange;
        private System.Windows.Forms.Panel panelMetricMembers;
        private System.Windows.Forms.Label lblMembersTitle;
        private System.Windows.Forms.Label lblMembersValue;
        private System.Windows.Forms.Label lblMembersChange;
        private System.Windows.Forms.Panel panelMetricBorrowed;
        private System.Windows.Forms.Label lblBorrowedTitle;
        private System.Windows.Forms.Label lblBorrowedValue;
        private System.Windows.Forms.Label lblBorrowedChange;
        private System.Windows.Forms.Panel panelMetricOverdue;
        private System.Windows.Forms.Label lblOverdueTitle;
        private System.Windows.Forms.Label lblOverdueValue;
        private System.Windows.Forms.Label lblOverdueChange;
        private System.Windows.Forms.Panel panelMetricFines;
        private System.Windows.Forms.Label lblFinesTitle;
        private System.Windows.Forms.Label lblFinesValue;
        private System.Windows.Forms.Label lblFinesChange;
        private System.Windows.Forms.Panel panelMetricReservations;
        private System.Windows.Forms.Label lblReservationsTitle;
        private System.Windows.Forms.Label lblReservationsValue;
        private System.Windows.Forms.Label lblReservationsChange;
        private System.Windows.Forms.Panel panelBarChart;
        private System.Windows.Forms.Label lblBarChartTitle;
        private System.Windows.Forms.Panel panelPieChart;
        private System.Windows.Forms.Label lblPieChartTitle;
        private System.Windows.Forms.Panel panelRecentActivities;
        private System.Windows.Forms.Label lblRecentActivitiesTitle;
        private System.Windows.Forms.Panel panelActivitiesList;
    }
}