namespace Project5LMS.Forms.LibraryStaff.Dashboard
{
    partial class StaffDashboardForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            this.panelSidebar = new System.Windows.Forms.Panel();
            this.btnLogout = new System.Windows.Forms.Button();
            this.lblLibraryStaff = new System.Windows.Forms.Label();
            this.panelSeparator = new System.Windows.Forms.Panel();
            this.btnSearch = new System.Windows.Forms.Button();
            this.btnInventory = new System.Windows.Forms.Button();
            this.btnFines = new System.Windows.Forms.Button();
            this.btnReservations = new System.Windows.Forms.Button();
            this.btnCirculation = new System.Windows.Forms.Button();
            this.btnCatalog = new System.Windows.Forms.Button();
            this.btnMembers = new System.Windows.Forms.Button();
            this.btnDashboard = new System.Windows.Forms.Button();
            this.lblSubtitleSidebar = new System.Windows.Forms.Label();
            this.lblTitleSidebar = new System.Windows.Forms.Label();
            this.panelMainContent = new System.Windows.Forms.Panel();
            this.panelMainContainer = new System.Windows.Forms.Panel();
            this.panelBottomSection = new System.Windows.Forms.Panel();
            this.panelOverdueBooks = new System.Windows.Forms.Panel();
            this.panelOverdueBooksList = new System.Windows.Forms.Panel();
            this.lblOverdueBooksTitle = new System.Windows.Forms.Label();
            this.panelRecentActivity = new System.Windows.Forms.Panel();
            this.lblRecentActivityTitle = new System.Windows.Forms.Label();
            this.listViewRecentActivity = new System.Windows.Forms.ListView();
            this.panelMetricsContainer = new System.Windows.Forms.Panel();
            this.panelMetricPendingFines = new System.Windows.Forms.Panel();
            this.lblPendingFinesChange = new System.Windows.Forms.Label();
            this.lblPendingFinesValue = new System.Windows.Forms.Label();
            this.lblPendingFinesTitle = new System.Windows.Forms.Label();
            this.panelMetricActiveLoans = new System.Windows.Forms.Panel();
            this.lblActiveLoansChange = new System.Windows.Forms.Label();
            this.lblActiveLoansValue = new System.Windows.Forms.Label();
            this.lblActiveLoansTitle = new System.Windows.Forms.Label();
            this.panelMetricBooksCatalog = new System.Windows.Forms.Panel();
            this.lblBooksCatalogChange = new System.Windows.Forms.Label();
            this.lblBooksCatalogValue = new System.Windows.Forms.Label();
            this.lblBooksCatalogTitle = new System.Windows.Forms.Label();
            this.panelMetricTotalMembers = new System.Windows.Forms.Panel();
            this.lblTotalMembersChange = new System.Windows.Forms.Label();
            this.lblTotalMembersValue = new System.Windows.Forms.Label();
            this.lblTotalMembersTitle = new System.Windows.Forms.Label();
            this.panelHeader = new System.Windows.Forms.Panel();
            this.lblSubtitle = new System.Windows.Forms.Label();
            this.lblTitle = new System.Windows.Forms.Label();
            this.panelSidebar.SuspendLayout();
            this.panelMainContent.SuspendLayout();
            this.panelMainContainer.SuspendLayout();
            this.panelBottomSection.SuspendLayout();
            this.panelOverdueBooks.SuspendLayout();
            this.panelOverdueBooksList.SuspendLayout();
            this.panelRecentActivity.SuspendLayout();
            this.panelMetricsContainer.SuspendLayout();
            this.panelMetricPendingFines.SuspendLayout();
            this.panelMetricActiveLoans.SuspendLayout();
            this.panelMetricBooksCatalog.SuspendLayout();
            this.panelMetricTotalMembers.SuspendLayout();
            this.panelHeader.SuspendLayout();
            this.SuspendLayout();
            this.panelSidebar.BackColor = System.Drawing.Color.Maroon;
            this.panelSidebar.Controls.Add(this.btnLogout);
            this.panelSidebar.Controls.Add(this.lblLibraryStaff);
            this.panelSidebar.Controls.Add(this.panelSeparator);
            this.panelSidebar.Controls.Add(this.btnSearch);
            this.panelSidebar.Controls.Add(this.btnInventory);
            this.panelSidebar.Controls.Add(this.btnFines);
            this.panelSidebar.Controls.Add(this.btnReservations);
            this.panelSidebar.Controls.Add(this.btnCirculation);
            this.panelSidebar.Controls.Add(this.btnCatalog);
            this.panelSidebar.Controls.Add(this.btnMembers);
            this.panelSidebar.Controls.Add(this.btnDashboard);
            this.panelSidebar.Controls.Add(this.lblSubtitleSidebar);
            this.panelSidebar.Controls.Add(this.lblTitleSidebar);
            this.panelSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelSidebar.Location = new System.Drawing.Point(0, 0);
            this.panelSidebar.Name = "panelSidebar";
            this.panelSidebar.Padding = new System.Windows.Forms.Padding(15, 24, 15, 24);
            this.panelSidebar.Size = new System.Drawing.Size(210, 800);
            this.panelSidebar.TabIndex = 0;
            this.btnLogout.BackColor = System.Drawing.Color.Maroon;
            this.btnLogout.FlatAppearance.BorderSize = 0;
            this.btnLogout.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLogout.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLogout.ForeColor = System.Drawing.Color.White;
            this.btnLogout.Location = new System.Drawing.Point(15, 748);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.Size = new System.Drawing.Size(180, 37);
            this.btnLogout.TabIndex = 12;
            this.btnLogout.Text = "🚪 Logout";
            this.btnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.UseVisualStyleBackColor = false;
            this.btnLogout.Click += new System.EventHandler(this.btnLogout_Click);
            this.lblLibraryStaff.AutoSize = true;
            this.lblLibraryStaff.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblLibraryStaff.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.lblLibraryStaff.Location = new System.Drawing.Point(15, 691);
            this.lblLibraryStaff.Name = "lblLibraryStaff";
            this.lblLibraryStaff.Size = new System.Drawing.Size(82, 19);
            this.lblLibraryStaff.TabIndex = 11;
            this.lblLibraryStaff.Text = "Library Staff";
            this.panelSeparator.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.panelSeparator.Location = new System.Drawing.Point(15, 674);
            this.panelSeparator.Name = "panelSeparator";
            this.panelSeparator.Size = new System.Drawing.Size(180, 1);
            this.panelSeparator.TabIndex = 10;
            this.btnSearch.BackColor = System.Drawing.Color.Maroon;
            this.btnSearch.FlatAppearance.BorderSize = 0;
            this.btnSearch.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSearch.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSearch.ForeColor = System.Drawing.Color.White;
            this.btnSearch.Location = new System.Drawing.Point(15, 447);
            this.btnSearch.Name = "btnSearch";
            this.btnSearch.Size = new System.Drawing.Size(180, 41);
            this.btnSearch.TabIndex = 9;
            this.btnSearch.Text = "🔍 Search";
            this.btnSearch.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSearch.UseVisualStyleBackColor = false;
            this.btnSearch.Click += new System.EventHandler(this.btnSearch_Click);
            this.btnInventory.BackColor = System.Drawing.Color.Maroon;
            this.btnInventory.FlatAppearance.BorderSize = 0;
            this.btnInventory.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnInventory.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInventory.ForeColor = System.Drawing.Color.White;
            this.btnInventory.Location = new System.Drawing.Point(15, 406);
            this.btnInventory.Name = "btnInventory";
            this.btnInventory.Size = new System.Drawing.Size(180, 41);
            this.btnInventory.TabIndex = 8;
            this.btnInventory.Text = "📦 Inventory";
            this.btnInventory.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInventory.UseVisualStyleBackColor = false;
            this.btnInventory.Click += new System.EventHandler(this.btnInventory_Click);
            this.btnFines.BackColor = System.Drawing.Color.Maroon;
            this.btnFines.FlatAppearance.BorderSize = 0;
            this.btnFines.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnFines.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFines.ForeColor = System.Drawing.Color.White;
            this.btnFines.Location = new System.Drawing.Point(15, 366);
            this.btnFines.Name = "btnFines";
            this.btnFines.Size = new System.Drawing.Size(180, 41);
            this.btnFines.TabIndex = 7;
            this.btnFines.Text = "💰 Fines";
            this.btnFines.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFines.UseVisualStyleBackColor = false;
            this.btnFines.Click += new System.EventHandler(this.btnFines_Click);
            this.btnReservations.BackColor = System.Drawing.Color.Maroon;
            this.btnReservations.FlatAppearance.BorderSize = 0;
            this.btnReservations.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnReservations.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReservations.ForeColor = System.Drawing.Color.White;
            this.btnReservations.Location = new System.Drawing.Point(15, 325);
            this.btnReservations.Name = "btnReservations";
            this.btnReservations.Size = new System.Drawing.Size(180, 41);
            this.btnReservations.TabIndex = 6;
            this.btnReservations.Text = "📋 Reservations";
            this.btnReservations.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReservations.UseVisualStyleBackColor = false;
            this.btnReservations.Click += new System.EventHandler(this.btnReservations_Click);
            this.btnCirculation.BackColor = System.Drawing.Color.Maroon;
            this.btnCirculation.FlatAppearance.BorderSize = 0;
            this.btnCirculation.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCirculation.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCirculation.ForeColor = System.Drawing.Color.White;
            this.btnCirculation.Location = new System.Drawing.Point(15, 284);
            this.btnCirculation.Name = "btnCirculation";
            this.btnCirculation.Size = new System.Drawing.Size(180, 41);
            this.btnCirculation.TabIndex = 5;
            this.btnCirculation.Text = "🔄 Circulation";
            this.btnCirculation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCirculation.UseVisualStyleBackColor = false;
            this.btnCirculation.Click += new System.EventHandler(this.btnCirculation_Click);
            this.btnCatalog.BackColor = System.Drawing.Color.Maroon;
            this.btnCatalog.FlatAppearance.BorderSize = 0;
            this.btnCatalog.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCatalog.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCatalog.ForeColor = System.Drawing.Color.White;
            this.btnCatalog.Location = new System.Drawing.Point(15, 244);
            this.btnCatalog.Name = "btnCatalog";
            this.btnCatalog.Size = new System.Drawing.Size(180, 41);
            this.btnCatalog.TabIndex = 4;
            this.btnCatalog.Text = "📚 Catalog";
            this.btnCatalog.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCatalog.UseVisualStyleBackColor = false;
            this.btnCatalog.Click += new System.EventHandler(this.btnCatalog_Click);
            this.btnMembers.BackColor = System.Drawing.Color.Maroon;
            this.btnMembers.FlatAppearance.BorderSize = 0;
            this.btnMembers.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMembers.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMembers.ForeColor = System.Drawing.Color.White;
            this.btnMembers.Location = new System.Drawing.Point(15, 203);
            this.btnMembers.Name = "btnMembers";
            this.btnMembers.Size = new System.Drawing.Size(180, 41);
            this.btnMembers.TabIndex = 3;
            this.btnMembers.Text = "👥 Members";
            this.btnMembers.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMembers.UseVisualStyleBackColor = false;
            this.btnMembers.Click += new System.EventHandler(this.btnMembers_Click);
            this.btnDashboard.BackColor = System.Drawing.Color.Maroon;
            this.btnDashboard.FlatAppearance.BorderSize = 0;
            this.btnDashboard.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnDashboard.Font = new System.Drawing.Font("Segoe UI", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.Location = new System.Drawing.Point(15, 162);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.Size = new System.Drawing.Size(180, 41);
            this.btnDashboard.TabIndex = 2;
            this.btnDashboard.Text = "📊 Dashboard";
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.UseVisualStyleBackColor = false;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click);
            this.lblSubtitleSidebar.AutoSize = true;
            this.lblSubtitleSidebar.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSubtitleSidebar.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.lblSubtitleSidebar.Location = new System.Drawing.Point(18, 58);
            this.lblSubtitleSidebar.Name = "lblSubtitleSidebar";
            this.lblSubtitleSidebar.Size = new System.Drawing.Size(139, 19);
            this.lblSubtitleSidebar.TabIndex = 1;
            this.lblSubtitleSidebar.Text = "Management System";
            this.lblSubtitleSidebar.Click += new System.EventHandler(this.lblSubtitleSidebar_Click);
            this.lblTitleSidebar.AutoSize = true;
            this.lblTitleSidebar.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitleSidebar.ForeColor = System.Drawing.Color.White;
            this.lblTitleSidebar.Location = new System.Drawing.Point(15, 24);
            this.lblTitleSidebar.Name = "lblTitleSidebar";
            this.lblTitleSidebar.Size = new System.Drawing.Size(149, 32);
            this.lblTitleSidebar.TabIndex = 0;
            this.lblTitleSidebar.Text = "UM Library ";
            this.panelMainContent.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(250)))), ((int)(((byte)(250)))));
            this.panelMainContent.Controls.Add(this.panelMainContainer);
            this.panelMainContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMainContent.Location = new System.Drawing.Point(210, 0);
            this.panelMainContent.Margin = new System.Windows.Forms.Padding(0);
            this.panelMainContent.Name = "panelMainContent";
            this.panelMainContent.Size = new System.Drawing.Size(990, 800);
            this.panelMainContent.TabIndex = 1;
            this.panelMainContainer.AutoScroll = true;
            this.panelMainContainer.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(250)))), ((int)(((byte)(250)))));
            this.panelMainContainer.Controls.Add(this.panelBottomSection);
            this.panelMainContainer.Controls.Add(this.panelMetricsContainer);
            this.panelMainContainer.Controls.Add(this.panelHeader);
            this.panelMainContainer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelMainContainer.Location = new System.Drawing.Point(0, 0);
            this.panelMainContainer.Margin = new System.Windows.Forms.Padding(0);
            this.panelMainContainer.Name = "panelMainContainer";
            this.panelMainContainer.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelMainContainer.Size = new System.Drawing.Size(990, 800);
            this.panelMainContainer.TabIndex = 0;
            this.panelBottomSection.Controls.Add(this.panelOverdueBooks);
            this.panelBottomSection.Controls.Add(this.panelRecentActivity);
            this.panelBottomSection.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelBottomSection.Location = new System.Drawing.Point(15, 274);
            this.panelBottomSection.Margin = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.panelBottomSection.Name = "panelBottomSection";
            this.panelBottomSection.Size = new System.Drawing.Size(960, 510);
            this.panelBottomSection.TabIndex = 2;
            this.panelOverdueBooks.BackColor = System.Drawing.Color.White;
            this.panelOverdueBooks.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelOverdueBooks.Controls.Add(this.panelOverdueBooksList);
            this.panelOverdueBooks.Dock = System.Windows.Forms.DockStyle.Right;
            this.panelOverdueBooks.Location = new System.Drawing.Point(483, 0);
            this.panelOverdueBooks.Margin = new System.Windows.Forms.Padding(0, 0, 8, 0);
            this.panelOverdueBooks.Name = "panelOverdueBooks";
            this.panelOverdueBooks.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelOverdueBooks.Size = new System.Drawing.Size(477, 510);
            this.panelOverdueBooks.TabIndex = 1;
            this.panelOverdueBooksList.AutoScroll = true;
            this.panelOverdueBooksList.Controls.Add(this.lblOverdueBooksTitle);
            this.panelOverdueBooksList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelOverdueBooksList.Location = new System.Drawing.Point(15, 16);
            this.panelOverdueBooksList.Name = "panelOverdueBooksList";
            this.panelOverdueBooksList.Padding = new System.Windows.Forms.Padding(0, 8, 0, 0);
            this.panelOverdueBooksList.Size = new System.Drawing.Size(445, 476);
            this.panelOverdueBooksList.TabIndex = 0;
            this.lblOverdueBooksTitle.AutoSize = true;
            this.lblOverdueBooksTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblOverdueBooksTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblOverdueBooksTitle.Location = new System.Drawing.Point(3, 6);
            this.lblOverdueBooksTitle.Name = "lblOverdueBooksTitle";
            this.lblOverdueBooksTitle.Size = new System.Drawing.Size(175, 25);
            this.lblOverdueBooksTitle.TabIndex = 1;
            this.lblOverdueBooksTitle.Text = "⚠️ Overdue Books";
            this.panelRecentActivity.BackColor = System.Drawing.Color.White;
            this.panelRecentActivity.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panelRecentActivity.Controls.Add(this.lblRecentActivityTitle);
            this.panelRecentActivity.Controls.Add(this.listViewRecentActivity);
            this.panelRecentActivity.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRecentActivity.Location = new System.Drawing.Point(0, 0);
            this.panelRecentActivity.Margin = new System.Windows.Forms.Padding(0);
            this.panelRecentActivity.Name = "panelRecentActivity";
            this.panelRecentActivity.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelRecentActivity.Size = new System.Drawing.Size(960, 510);
            this.panelRecentActivity.TabIndex = 0;
            this.lblRecentActivityTitle.AutoSize = true;
            this.lblRecentActivityTitle.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblRecentActivityTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblRecentActivityTitle.Location = new System.Drawing.Point(19, 22);
            this.lblRecentActivityTitle.Name = "lblRecentActivityTitle";
            this.lblRecentActivityTitle.Size = new System.Drawing.Size(143, 25);
            this.lblRecentActivityTitle.TabIndex = 1;
            this.lblRecentActivityTitle.Text = "Recent Activity";
            this.listViewRecentActivity.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.listViewRecentActivity.Dock = System.Windows.Forms.DockStyle.Fill;
            this.listViewRecentActivity.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.listViewRecentActivity.FullRowSelect = true;
            this.listViewRecentActivity.HideSelection = false;
            this.listViewRecentActivity.Location = new System.Drawing.Point(15, 16);
            this.listViewRecentActivity.MultiSelect = false;
            this.listViewRecentActivity.Name = "listViewRecentActivity";
            this.listViewRecentActivity.OwnerDraw = true;
            this.listViewRecentActivity.Size = new System.Drawing.Size(928, 476);
            this.listViewRecentActivity.TabIndex = 0;
            this.listViewRecentActivity.UseCompatibleStateImageBehavior = false;
            this.listViewRecentActivity.View = System.Windows.Forms.View.Details;
            this.panelMetricsContainer.Controls.Add(this.panelMetricPendingFines);
            this.panelMetricsContainer.Controls.Add(this.panelMetricActiveLoans);
            this.panelMetricsContainer.Controls.Add(this.panelMetricBooksCatalog);
            this.panelMetricsContainer.Controls.Add(this.panelMetricTotalMembers);
            this.panelMetricsContainer.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelMetricsContainer.Location = new System.Drawing.Point(15, 95);
            this.panelMetricsContainer.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.panelMetricsContainer.Name = "panelMetricsContainer";
            this.panelMetricsContainer.Size = new System.Drawing.Size(960, 179);
            this.panelMetricsContainer.TabIndex = 1;
            this.panelMetricPendingFines.BackColor = System.Drawing.Color.White;
            this.panelMetricPendingFines.Controls.Add(this.lblPendingFinesChange);
            this.panelMetricPendingFines.Controls.Add(this.lblPendingFinesValue);
            this.panelMetricPendingFines.Controls.Add(this.lblPendingFinesTitle);
            this.panelMetricPendingFines.Location = new System.Drawing.Point(724, 0);
            this.panelMetricPendingFines.Name = "panelMetricPendingFines";
            this.panelMetricPendingFines.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelMetricPendingFines.Size = new System.Drawing.Size(236, 163);
            this.panelMetricPendingFines.TabIndex = 3;
            this.lblPendingFinesChange.AutoSize = true;
            this.lblPendingFinesChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPendingFinesChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(53)))), ((int)(((byte)(69)))));
            this.lblPendingFinesChange.Location = new System.Drawing.Point(15, 122);
            this.lblPendingFinesChange.Name = "lblPendingFinesChange";
            this.lblPendingFinesChange.Size = new System.Drawing.Size(34, 19);
            this.lblPendingFinesChange.TabIndex = 2;
            this.lblPendingFinesChange.Text = "-5%";
            this.lblPendingFinesValue.AutoSize = true;
            this.lblPendingFinesValue.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPendingFinesValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPendingFinesValue.Location = new System.Drawing.Point(15, 65);
            this.lblPendingFinesValue.Name = "lblPendingFinesValue";
            this.lblPendingFinesValue.Size = new System.Drawing.Size(142, 51);
            this.lblPendingFinesValue.TabIndex = 1;
            this.lblPendingFinesValue.Text = "$1,240";
            this.lblPendingFinesTitle.AutoSize = true;
            this.lblPendingFinesTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPendingFinesTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblPendingFinesTitle.Location = new System.Drawing.Point(15, 16);
            this.lblPendingFinesTitle.Name = "lblPendingFinesTitle";
            this.lblPendingFinesTitle.Size = new System.Drawing.Size(144, 21);
            this.lblPendingFinesTitle.TabIndex = 0;
            this.lblPendingFinesTitle.Text = "💰 Pending Fines";
            this.panelMetricActiveLoans.BackColor = System.Drawing.Color.White;
            this.panelMetricActiveLoans.Controls.Add(this.lblActiveLoansChange);
            this.panelMetricActiveLoans.Controls.Add(this.lblActiveLoansValue);
            this.panelMetricActiveLoans.Controls.Add(this.lblActiveLoansTitle);
            this.panelMetricActiveLoans.Location = new System.Drawing.Point(483, 0);
            this.panelMetricActiveLoans.Name = "panelMetricActiveLoans";
            this.panelMetricActiveLoans.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelMetricActiveLoans.Size = new System.Drawing.Size(236, 163);
            this.panelMetricActiveLoans.TabIndex = 2;
            this.lblActiveLoansChange.AutoSize = true;
            this.lblActiveLoansChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblActiveLoansChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(167)))), ((int)(((byte)(69)))));
            this.lblActiveLoansChange.Location = new System.Drawing.Point(15, 122);
            this.lblActiveLoansChange.Name = "lblActiveLoansChange";
            this.lblActiveLoansChange.Size = new System.Drawing.Size(38, 19);
            this.lblActiveLoansChange.TabIndex = 2;
            this.lblActiveLoansChange.Text = "+8%";
            this.lblActiveLoansValue.AutoSize = true;
            this.lblActiveLoansValue.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.lblActiveLoansValue.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblActiveLoansValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblActiveLoansValue.Location = new System.Drawing.Point(15, 65);
            this.lblActiveLoansValue.Name = "lblActiveLoansValue";
            this.lblActiveLoansValue.Size = new System.Drawing.Size(88, 51);
            this.lblActiveLoansValue.TabIndex = 1;
            this.lblActiveLoansValue.Text = "342";
            this.lblActiveLoansTitle.AutoSize = true;
            this.lblActiveLoansTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblActiveLoansTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblActiveLoansTitle.Location = new System.Drawing.Point(15, 16);
            this.lblActiveLoansTitle.Name = "lblActiveLoansTitle";
            this.lblActiveLoansTitle.Size = new System.Drawing.Size(133, 21);
            this.lblActiveLoansTitle.TabIndex = 0;
            this.lblActiveLoansTitle.Text = "📖 Active Loans";
            this.panelMetricBooksCatalog.BackColor = System.Drawing.Color.White;
            this.panelMetricBooksCatalog.Controls.Add(this.lblBooksCatalogChange);
            this.panelMetricBooksCatalog.Controls.Add(this.lblBooksCatalogValue);
            this.panelMetricBooksCatalog.Controls.Add(this.lblBooksCatalogTitle);
            this.panelMetricBooksCatalog.Location = new System.Drawing.Point(242, 0);
            this.panelMetricBooksCatalog.Name = "panelMetricBooksCatalog";
            this.panelMetricBooksCatalog.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelMetricBooksCatalog.Size = new System.Drawing.Size(236, 163);
            this.panelMetricBooksCatalog.TabIndex = 1;
            this.lblBooksCatalogChange.AutoSize = true;
            this.lblBooksCatalogChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBooksCatalogChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(167)))), ((int)(((byte)(69)))));
            this.lblBooksCatalogChange.Location = new System.Drawing.Point(15, 122);
            this.lblBooksCatalogChange.Name = "lblBooksCatalogChange";
            this.lblBooksCatalogChange.Size = new System.Drawing.Size(38, 19);
            this.lblBooksCatalogChange.TabIndex = 2;
            this.lblBooksCatalogChange.Text = "+3%";
            this.lblBooksCatalogValue.AutoSize = true;
            this.lblBooksCatalogValue.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBooksCatalogValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblBooksCatalogValue.Location = new System.Drawing.Point(15, 65);
            this.lblBooksCatalogValue.Name = "lblBooksCatalogValue";
            this.lblBooksCatalogValue.Size = new System.Drawing.Size(120, 51);
            this.lblBooksCatalogValue.TabIndex = 1;
            this.lblBooksCatalogValue.Text = "8,932";
            this.lblBooksCatalogTitle.AutoSize = true;
            this.lblBooksCatalogTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblBooksCatalogTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblBooksCatalogTitle.Location = new System.Drawing.Point(15, 16);
            this.lblBooksCatalogTitle.Name = "lblBooksCatalogTitle";
            this.lblBooksCatalogTitle.Size = new System.Drawing.Size(161, 21);
            this.lblBooksCatalogTitle.TabIndex = 0;
            this.lblBooksCatalogTitle.Text = "📚 Books in Catalog";
            this.panelMetricTotalMembers.BackColor = System.Drawing.Color.White;
            this.panelMetricTotalMembers.Controls.Add(this.lblTotalMembersChange);
            this.panelMetricTotalMembers.Controls.Add(this.lblTotalMembersValue);
            this.panelMetricTotalMembers.Controls.Add(this.lblTotalMembersTitle);
            this.panelMetricTotalMembers.Location = new System.Drawing.Point(0, 0);
            this.panelMetricTotalMembers.Name = "panelMetricTotalMembers";
            this.panelMetricTotalMembers.Padding = new System.Windows.Forms.Padding(15, 16, 15, 16);
            this.panelMetricTotalMembers.Size = new System.Drawing.Size(236, 163);
            this.panelMetricTotalMembers.TabIndex = 0;
            this.lblTotalMembersChange.AutoSize = true;
            this.lblTotalMembersChange.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalMembersChange.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(167)))), ((int)(((byte)(69)))));
            this.lblTotalMembersChange.Location = new System.Drawing.Point(15, 122);
            this.lblTotalMembersChange.Name = "lblTotalMembersChange";
            this.lblTotalMembersChange.Size = new System.Drawing.Size(46, 19);
            this.lblTotalMembersChange.TabIndex = 2;
            this.lblTotalMembersChange.Text = "+12%";
            this.lblTotalMembersValue.AutoSize = true;
            this.lblTotalMembersValue.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalMembersValue.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblTotalMembersValue.Location = new System.Drawing.Point(15, 65);
            this.lblTotalMembersValue.Name = "lblTotalMembersValue";
            this.lblTotalMembersValue.Size = new System.Drawing.Size(120, 51);
            this.lblTotalMembersValue.TabIndex = 1;
            this.lblTotalMembersValue.Text = "1,247";
            this.lblTotalMembersTitle.AutoSize = true;
            this.lblTotalMembersTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTotalMembersTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblTotalMembersTitle.Location = new System.Drawing.Point(15, 16);
            this.lblTotalMembersTitle.Name = "lblTotalMembersTitle";
            this.lblTotalMembersTitle.Size = new System.Drawing.Size(150, 21);
            this.lblTotalMembersTitle.TabIndex = 0;
            this.lblTotalMembersTitle.Text = "👥 Total Members";
            this.panelHeader.Controls.Add(this.lblSubtitle);
            this.panelHeader.Controls.Add(this.lblTitle);
            this.panelHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelHeader.Location = new System.Drawing.Point(15, 16);
            this.panelHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 8);
            this.panelHeader.Name = "panelHeader";
            this.panelHeader.Size = new System.Drawing.Size(960, 79);
            this.panelHeader.TabIndex = 0;
            this.lblSubtitle.AutoSize = true;
            this.lblSubtitle.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            this.lblSubtitle.Location = new System.Drawing.Point(13, 52);
            this.lblSubtitle.Name = "lblSubtitle";
            this.lblSubtitle.Size = new System.Drawing.Size(270, 19);
            this.lblSubtitle.TabIndex = 1;
            this.lblSubtitle.Text = "Monitor library operations and key metrics";
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblTitle.Location = new System.Drawing.Point(9, 8);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(184, 45);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Dashboard";
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1200, 800);
            this.Controls.Add(this.panelMainContent);
            this.Controls.Add(this.panelSidebar);
            this.Name = "StaffDashboardForm";
            this.Text = "LibraryMS - Management System";
            this.Load += new System.EventHandler(this.StaffDashboardForm_Load);
            this.panelSidebar.ResumeLayout(false);
            this.panelSidebar.PerformLayout();
            this.panelMainContent.ResumeLayout(false);
            this.panelMainContainer.ResumeLayout(false);
            this.panelBottomSection.ResumeLayout(false);
            this.panelOverdueBooks.ResumeLayout(false);
            this.panelOverdueBooksList.ResumeLayout(false);
            this.panelOverdueBooksList.PerformLayout();
            this.panelRecentActivity.ResumeLayout(false);
            this.panelRecentActivity.PerformLayout();
            this.panelMetricsContainer.ResumeLayout(false);
            this.panelMetricPendingFines.ResumeLayout(false);
            this.panelMetricPendingFines.PerformLayout();
            this.panelMetricActiveLoans.ResumeLayout(false);
            this.panelMetricActiveLoans.PerformLayout();
            this.panelMetricBooksCatalog.ResumeLayout(false);
            this.panelMetricBooksCatalog.PerformLayout();
            this.panelMetricTotalMembers.ResumeLayout(false);
            this.panelMetricTotalMembers.PerformLayout();
            this.panelHeader.ResumeLayout(false);
            this.panelHeader.PerformLayout();
            this.ResumeLayout(false);
        }
        #endregion
        private System.Windows.Forms.Panel panelSidebar;
        private System.Windows.Forms.Label lblTitleSidebar;
        private System.Windows.Forms.Label lblSubtitleSidebar;
        private System.Windows.Forms.Button btnDashboard;
        private System.Windows.Forms.Button btnMembers;
        private System.Windows.Forms.Button btnCatalog;
        private System.Windows.Forms.Button btnCirculation;
        private System.Windows.Forms.Button btnReservations;
        private System.Windows.Forms.Button btnFines;
        private System.Windows.Forms.Button btnInventory;
        private System.Windows.Forms.Button btnSearch;
        private System.Windows.Forms.Panel panelSeparator;
        private System.Windows.Forms.Label lblLibraryStaff;
        private System.Windows.Forms.Button btnLogout;
        private System.Windows.Forms.Panel panelMainContent;
        private System.Windows.Forms.Panel panelMainContainer;
        private System.Windows.Forms.Panel panelHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.Label lblSubtitle;
        private System.Windows.Forms.Panel panelMetricsContainer;
        private System.Windows.Forms.Panel panelMetricTotalMembers;
        private System.Windows.Forms.Label lblTotalMembersTitle;
        private System.Windows.Forms.Label lblTotalMembersValue;
        private System.Windows.Forms.Label lblTotalMembersChange;
        private System.Windows.Forms.Panel panelMetricBooksCatalog;
        private System.Windows.Forms.Label lblBooksCatalogTitle;
        private System.Windows.Forms.Label lblBooksCatalogValue;
        private System.Windows.Forms.Label lblBooksCatalogChange;
        private System.Windows.Forms.Panel panelMetricActiveLoans;
        private System.Windows.Forms.Label lblActiveLoansTitle;
        private System.Windows.Forms.Label lblActiveLoansValue;
        private System.Windows.Forms.Label lblActiveLoansChange;
        private System.Windows.Forms.Panel panelMetricPendingFines;
        private System.Windows.Forms.Label lblPendingFinesTitle;
        private System.Windows.Forms.Label lblPendingFinesValue;
        private System.Windows.Forms.Label lblPendingFinesChange;
        private System.Windows.Forms.Panel panelBottomSection;
        private System.Windows.Forms.Panel panelRecentActivity;
        private System.Windows.Forms.Label lblRecentActivityTitle;
        private System.Windows.Forms.ListView listViewRecentActivity;
        private System.Windows.Forms.Panel panelOverdueBooks;
        private System.Windows.Forms.Label lblOverdueBooksTitle;
        private System.Windows.Forms.Panel panelOverdueBooksList;
    }
}